'use strict';

const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const programme = require('../scripts/toolkit-github-program-state-v5.cjs');
const governance = require('../scripts/toolkit-github-governance-review-reconciler.cjs');
const receipt = require('../scripts/toolkit-github-program-receipt.cjs');

const repository = programme.REPOSITORY;
const decision = programme.createRecoveryDecision();
const PARENT_BODY = "<!-- AI-AGENT-TOOLKIT:GITHUB-PROGRAM-PARENT:BEGIN v5 -->\n# Programme dashboard\n\n## Goal\nDeliver the six-stage Toolkit programme through truthful, deterministic, source-traceable programme views.\n\n## Programme status\n| Field | Value |\n| --- | --- |\n| Aggregate programme state | HELD |\n| Concurrency mode | SINGLE_DEFAULT |\n| Active lanes | 1 |\n| Max lanes | 1 |\n| Current child IDs | #359 |\n| Programme finality state | HELD |\n\n## Active work\n| Child | State | Epoch / Gate | Candidate / PR | Material hold |\n| --- | --- | --- | --- | --- |\n| #359 - S2 — Productize retained skills + native host adapters | ACTIVE | E3 / G4 | PR #366 @ a7dcb69da43100c5411076008307a221e89b720f | None |\n\n## Children\n| Child | Lifecycle | Dependencies | Outcome |\n| --- | --- | --- | --- |\n| #358 - S1 — Canonical topology collapse + permanent Ledger retirement | COMPLETED | None | S1 — Canonical topology collapse + permanent Ledger retirement is completed with retained evidence. |\n| #359 - S2 — Productize retained skills + native host adapters | CURRENT | None | S2 — Productize retained skills + native host adapters is current in E3 at G4. |\n| #360 - S3 — Repository Loop Manager + trusted CI live integration | QUEUED | #358 | S3 — Repository Loop Manager + trusted CI live integration is queued behind its declared dependencies. |\n| #361 - S4 — Official n8n Skills + API-first workflow transport | QUEUED | #358, #359, #360 | S4 — Official n8n Skills + API-first workflow transport is queued behind its declared dependencies. |\n| #362 - S5 — External authority, secrets + hosted operations | QUEUED | #358, #359, #360 | S5 — External authority, secrets + hosted operations is queued behind its declared dependencies. |\n| #363 - S6 — Native UAT + final whole-Toolkit assurance | QUEUED | #358, #359, #360, #361, #362 | S6 — Native UAT + final whole-Toolkit assurance is queued behind its declared dependencies. |\n\n## Progress\n| Metric | Value |\n| --- | --- |\n| Completed children / total | 1 / 6 |\n| Retired children | 0 |\n| Accepted or retired epochs / total | 3 / 9 |\n| Active lanes | 1 |\n| Web-decision-required lanes | 0 |\n\n## Major holds\nNone\n\n## Additional context\nNone\n\n<!-- AI-AGENT-TOOLKIT:GITHUB-PROGRAM-CANONICAL v5 eyJlbnZlbG9wZSI6eyJjYW5vbmljYWxfZGlnZXN0IjoiYTA5ZmRhZmE2Yjc3YWQ4NTYyNDI5OGNlZWE0ODhhNWMzNDJkMDBhMDcwMDIxOGRlNjJiYTIyNzZlZDA1MDI4MCIsImV4dGVuc2lvbl9kaWdlc3QiOiI0ZjUzY2RhMThjMmJhYTBjMDM1NGJiNWY5YTNlY2JlNWVkMTJhYjRkOGUxMWJhODczYzJmMTExNjEyMDJiOTQ1Iiwia2luZCI6InBhcmVudCIsIm51bWJlciI6MjQwLCJwYXJlbnRfaXNzdWUiOjI0MCwicHJvamVjdGlvbl9kaWdlc3QiOiI3ZjY4OGNmM2M5MzIxOGYyMzA4MWJhMDQ0NzFjMWYwYjZjYTdlNGMxMjA2ZDk3ODBmMjIxMjI0NmM3ODI5ZDRjIiwicmVwb3NpdG9yeSI6IndlaWp1bnN3ai9haS1hZ2VudC10b29sa2l0Iiwic2NoZW1hIjoidG9vbGtpdC5naXRodWItcHJvZ3JhbS5wcm9qZWN0aW9uLnYxIn0sInN0YXRlIjp7ImFjdGl2ZV9sYW5lcyI6W3siY2FuZGlkYXRlIjp7ImJhc2VfcmVmIjoibWFpbiIsImJhc2Vfc2hhIjoiZTg2YTJkNzRmZDc3MWY2NTAwYWEwMmZlMDg5Mjk0MDkzM2JmNzY0NyIsImJyYW5jaCI6InNvbC9zMi1wcm9kdWN0aXNhdGlvbi1nMyIsImVwb2NoX2lkIjoiRTMiLCJoZWFkIjoiYTdkY2I2OWRhNDMxMDBjNTQxMTA3NjAwODMwN2EyMjFlODliNzIwZiIsInByIjozNjYsInRyZWUiOiIyYzg4NzgyZmEyNzRlNTAyZmI2YzhjNTEyNmQ1NTQ3MDExMmYzOGU5IiwidmVyc2lvbiI6IjIuMTIuMCJ9LCJjaGlsZF9pc3N1ZSI6MzU5LCJlcG9jaF9pZCI6IkUzIiwiZ2F0ZSI6Ikc0IiwiZ2F0ZV9yZXN1bHQiOm51bGwsImdhdGVfc3RhdGUiOiJBQ1RJVkUiLCJsYW5lX2lkIjoiY2hpbGQtMzU5Iiwid29ya19jbGFpbXMiOlt7Im1vZGUiOiJXUklURSIsIm9wZXJhdGlvbiI6ImNhbm9uaWNhbC10cmFuc2l0aW9uIiwicmVzb3VyY2UiOiJwcm9ncmFtbWUvY2hpbGQvMzU5In1dfV0sImNoaWxkcmVuIjpbeyJib3VuZGFyaWVzIjpbIktlZXAgY29tcGxldGVkIGFuZCBtZXJnZWQgUzEgc2NvcGUgY2xvc2VkLiIsIlMyIHRocm91Z2ggUzYgcmVtYWluIG91dHNpZGUgUzEuIl0sImRlbGl2ZXJhYmxlcyI6WyJDYW5vbmljYWwgVG9vbGtpdCB0b3BvbG9neSBjb2xsYXBzZS4iLCJQZXJtYW5lbnQgcmV0aXJlbWVudCBvZiBvYnNvbGV0ZSB0b3BvbG9neSBhbmQgZXh0ZXJuYWwgZXhlY3V0b3ItZXZhbHVhdGlvbiBMZWRnZXIgY291cGxpbmcuIl0sImRlcGVuZGVuY2llcyI6W10sImRvbmVfd2hlbiI6WyJDYW5vbmljYWwgc3VyZmFjZXMgYXJlIHJldGFpbmVkLCBvYnNvbGV0ZSB0b3BvbG9neSBhbmQgTGVkZ2VyIGNvdXBsaW5nIGFyZSBwZXJtYW5lbnRseSByZXRpcmVkLCBhbmQgY29tcGxldGVkIHNjb3BlIHJlbWFpbnMgY2xvc2VkLiJdLCJlbGk1IjoiVGhlIG9sZCBsYXlvdXQgd2FzIGNsZWFuZWQgdXAgYW5kIHRoaXMgZmluaXNoZWQgc3RlcCBzdGF5cyBjbG9zZWQuIiwiZXBvY2hzIjpbeyJldmlkZW5jZV9yZWYiOiJzMS1hY2NlcHRlZCIsImdhdGVzIjpbIkcxIiwiRzIiLCJHMyIsIkc0Il0sImlkIjoiUzEiLCJsb2NrIjoiREwtUzEtQ0FOT05JQ0FMLVRPUE9MT0dZLUNPTExBUFNFLTAwMS1HMiIsIm5hbWUiOiJTMSAtIENhbm9uaWNhbCB0b3BvbG9neSBjb2xsYXBzZSIsInB1cnBvc2UiOiJDYW5vbmljYWwgdG9wb2xvZ3kgY29sbGFwc2UiLCJ0ZXJtaW5hbF9kaXNwb3NpdGlvbiI6IkFDQ0VQVEVEIn1dLCJmaW5hbGl0eSI6eyJhdXRob3JpdHlfcmVmIjoiczEtYWNjZXB0ZWQiLCJzdGF0ZSI6Ik1FUkdFRCJ9LCJob2xkcyI6W10sImlzc3VlIjozNTgsImxpZmVjeWNsZSI6IkNPTVBMRVRFRCIsIm9iamVjdGl2ZSI6IkNvbGxhcHNlIFRvb2xraXQgdG8gY2Fub25pY2FsIHN1cmZhY2VzIGFuZCBwZXJtYW5lbnRseSByZXRpcmUgb2Jzb2xldGUgdG9wb2xvZ3kgcmVzaWR1ZS4iLCJvcmRlciI6MSwib3V0X29mX3Njb3BlIjpbIlJlb3BlbmluZyBjb21wbGV0ZWQgb3IgbWVyZ2VkIFMxIHNjb3BlLiIsIlMyIHRocm91Z2ggUzYgd29yay4iXSwicHJfcmVnaXN0cnkiOltdLCJzY29wZSI6WyJDb21wbGV0ZWQgUzEgdG9wb2xvZ3kgY29sbGFwc2UgYW5kIHBlcm1hbmVudCBvYnNvbGV0ZS9MZWRnZXIgY291cGxpbmcgcmV0aXJlbWVudC4iXSwic3VtbWFyeSI6IkNvbGxhcHNlIFRvb2xraXQgdG8gY2Fub25pY2FsIHN1cmZhY2VzIGFuZCBwZXJtYW5lbnRseSByZXRpcmUgb2Jzb2xldGUgdG9wb2xvZ3kgcmVzaWR1ZS4iLCJ0aXRsZSI6IlMxIOKAlCBDYW5vbmljYWwgdG9wb2xvZ3kgY29sbGFwc2UgKyBwZXJtYW5lbnQgTGVkZ2VyIHJldGlyZW1lbnQifSx7ImJvdW5kYXJpZXMiOlsiV2ViIG93bnMgZnJlc2ggRzQgZGlzcG9zaXRpb24sIEUzIGFjY2VwdGFuY2UsIFJlYWR5LCBtZXJnZSBhbmQgZmluYWxpdHkuIiwiRnJlc2ggRzQgaXMgYWN0aXZlIHdpdGggbm8gcmVzdWx0IHlldC4iLCJFNCBhbmQgUzMgdGhyb3VnaCBTNiBkbyBub3QgYmVnaW4gaW4gdGhpcyB0cmFuc2l0aW9uLiJdLCJkZWxpdmVyYWJsZXMiOlsiUmV0YWluZWQtc2tpbGwgcHJvZHVjdGlzYXRpb24uIiwiR2l0SHViIHByb2dyYW1tZSByZWNvbmNpbGVyIHY1LiIsIkZ1dHVyZSBFNCB0cnV0aGZ1bCBuYXRpdmUgYWRhcHRlcnMuIl0sImRlcGVuZGVuY2llcyI6W10sImRvbmVfd2hlbiI6WyJFMSBhbmQgRTIgcmVtYWluIGFjY2VwdGVkIHdpdGggcmV0YWluZWQgZXZpZGVuY2UuIiwiRTMgUmVwYWlyLTIsIHY1IG1pZ3JhdGlvbi9yZWFkYmFjay96ZXJvLWRlbHRhLCBjYW5vbmljYWwtZGF0YSBVWCBjb3JyZWN0aW9uLCBmcmVzaCBHNCBhbmQgV2ViIGFjY2VwdGFuY2UgYXJlIGNvbXBsZXRlLiIsIkU0IHRydXRoZnVsIG5hdGl2ZSBhZGFwdGVycyBhcmUgY29tcGxldGUgYW5kIFdlYiByZWNvcmRzIFMyIGZpbmFsaXR5LiJdLCJlbGk1IjoiVGhlIHByb2dyYW1tZSB0b29sIGlzIHJlcGFpcmVkIGFuZCBpdHMgZmluYWwgaW5kZXBlbmRlbnQgRTMgcmV2aWV3IGdhdGUgaXMgbm93IGFjdGl2ZSwgYnV0IG5vIHJlc3VsdCBvciBhY2NlcHRhbmNlIGV4aXN0cyB5ZXQuIiwiZXBvY2hzIjpbeyJldmlkZW5jZV9yZWYiOiJlMS1hY2NlcHRlZCIsImdhdGVzIjpbIkcxIiwiRzIiLCJHMyIsIkc0Il0sImlkIjoiRTEiLCJsb2NrIjoiREwtUzItQ1JFQVRJT04tR0FURS0wMDMiLCJuYW1lIjoiRTEgLSBDcmVhdGlvbiBHYXRlIiwicHVycG9zZSI6IkNyZWF0aW9uIGFuZCBhZG1pc3Npb24gZ2F0ZSIsInRlcm1pbmFsX2Rpc3Bvc2l0aW9uIjoiQUNDRVBURUQifSx7ImV2aWRlbmNlX3JlZiI6ImUyLWFjY2VwdGVkIiwiZ2F0ZXMiOlsiRzEiLCJHMiIsIkczIiwiRzQiXSwiaWQiOiJFMiIsImxvY2siOiJETC1TMi1QUk9EVUNULVBPUlRGT0xJTy0wMTUiLCJuYW1lIjoiRTIgLSBQcm9kdWN0IFBvcnRmb2xpbyIsInB1cnBvc2UiOiJSZXRhaW5lZCBwcm9kdWN0IHBvcnRmb2xpbyIsInRlcm1pbmFsX2Rpc3Bvc2l0aW9uIjoiQUNDRVBURUQifSx7ImV2aWRlbmNlX3JlZiI6bnVsbCwiZ2F0ZXMiOlsiRzEiLCJHMiIsIkczIiwiRzQiXSwiaWQiOiJFMyIsImxvY2siOiJETC1TMi1HSVRIVUItUFJPR1JBTS1DT05WRVJHRU5DRS0wMDIiLCJuYW1lIjoiRTMgLSBHaXRIdWIgUHJvZ3JhbW1lIFByb2R1Y3QiLCJwdXJwb3NlIjoiTWFuYWdlZCBHaXRIdWIgcHJvZ3JhbW1lIHJlY29uY2lsaWF0aW9uIiwidGVybWluYWxfZGlzcG9zaXRpb24iOm51bGx9LHsiZXZpZGVuY2VfcmVmIjpudWxsLCJnYXRlcyI6WyJHMSIsIkcyIiwiRzMiLCJHNCJdLCJpZCI6IkU0IiwibG9jayI6IkRMLVMyLU5BVElWRS1BREFQVEVSUy0wMDIiLCJuYW1lIjoiRTQgLSBOYXRpdmUgQWRhcHRlcnMiLCJwdXJwb3NlIjoiVHJ1dGhmdWwgbmF0aXZlIGhvc3QgYWRhcHRlcnMiLCJ0ZXJtaW5hbF9kaXNwb3NpdGlvbiI6bnVsbH1dLCJmaW5hbGl0eSI6eyJhdXRob3JpdHlfcmVmIjpudWxsLCJzdGF0ZSI6IkhFTEQifSwiaG9sZHMiOltdLCJpc3N1ZSI6MzU5LCJsaWZlY3ljbGUiOiJDVVJSRU5UIiwib2JqZWN0aXZlIjoiUHJvZHVjdGlzZSByZXRhaW5lZCBza2lsbHMsIGNvbXBsZXRlIHRoZSBHaXRIdWIgcHJvZ3JhbW1lIHJlY29uY2lsZXIsIHRoZW4gZmluaXNoIHRydXRoZnVsIG5hdGl2ZSBob3N0IGFkYXB0ZXJzLiIsIm9yZGVyIjoyLCJvdXRfb2Zfc2NvcGUiOlsiRzQgcmVzdWx0IG9yIEUzIGFjY2VwdGFuY2UgYmVmb3JlIHNlcGFyYXRlIFdlYiBhdXRob3JpdHkuIiwiUmVhZHksIG1lcmdlLCBmaW5hbGl0eSwgRTQgZXhlY3V0aW9uIGFuZCBTMyB0aHJvdWdoIFM2IHByb2dyZXNzaW9uLiJdLCJwcl9yZWdpc3RyeSI6W3siYWNjZXB0ZWRfZXZpZGVuY2VfcmVmIjpudWxsLCJjb21wbGV0ZXNfY2hpbGQiOmZhbHNlLCJlcG9jaF9pZCI6IkUzIiwicHIiOjM2NiwicmV0aXJlbWVudF9ldmlkZW5jZV9yZWYiOm51bGwsInJvbGUiOiJJTlRFUk1FRElBVEUiLCJzdGF0dXMiOiJBQ1RJVkUifV0sInNjb3BlIjpbIlJldGFpbmVkLXNraWxsIHByb2R1Y3Rpc2F0aW9uLCBHaXRIdWIgcHJvZ3JhbW1lIHJlY29uY2lsZXIgdjUgYW5kIGZ1dHVyZSBFNCB0cnV0aGZ1bCBuYXRpdmUgYWRhcHRlcnMuIiwiRnJlc2ggRTMgRzQgdHJhbnNpdGlvbiBhbmQgZXhhY3QtY2FuZGlkYXRlIHZhbGlkYXRpb24uIl0sInN1bW1hcnkiOiJFMSBhbmQgRTIgYXJlIGFjY2VwdGVkOyBFMyBSZXBhaXItMiBpbXBsZW1lbnRhdGlvbiwgdjUgbWlncmF0aW9uL3JlYWRiYWNrL3plcm8tZGVsdGEgYW5kIGRvZ2Zvb2QgVVggY29ycmVjdGlvbiBhcmUgYWNoaWV2ZWQ7IGZyZXNoIEc0IGlzIG5vdyBhY3RpdmUgd2l0aCBubyByZXN1bHQuIiwidGl0bGUiOiJTMiDigJQgUHJvZHVjdGl6ZSByZXRhaW5lZCBza2lsbHMgKyBuYXRpdmUgaG9zdCBhZGFwdGVycyJ9LHsiYm91bmRhcmllcyI6WyJDb25zZXF1ZW50aWFsIGxpdmUgb3IgcmVwb3NpdG9yeS1wcm90ZWN0aW9uIG11dGF0aW9uIHJlcXVpcmVzIGV4cGxpY2l0IGF1dGhvcml0eS4iLCJUaGlzIHF1ZXVlZCBjaGlsZCBkb2VzIG5vdCBzdGFydCB1bnRpbCBpdHMgZGVwZW5kZW5jaWVzIGFyZSBjb21wbGV0ZSBvciByZXRpcmVkLiJdLCJkZWxpdmVyYWJsZXMiOlsiUmVwb3NpdG9yeSBMb29wIE1hbmFnZXIgYW5kIHdvcmsgZ3JhcGguIiwiTGVhc2VzLCBmZW5jZXMsIGR1cmFibGUgcmVjb3ZlcnkgYW5kIGlkZW1wb3RlbmN5LiIsIkJvdW5kZWQgY29udmVyZ2VuY2Ugd2l0aCBhIHR3by1yZXBhaXIgc3RvcC4iLCJUcnVzdGVkIENJIGFuZCBwZXJtYW5lbnQgaG9zdC1iYWNrZWQgb3JjaGVzdHJhdGlvbi4iXSwiZGVwZW5kZW5jaWVzIjpbMzU4XSwiZG9uZV93aGVuIjpbIlRoZSBMb29wIE1hbmFnZXIsIHdvcmsgZ3JhcGgsIGxlYXNlcy9mZW5jZXMsIGR1cmFibGUgcmVjb3ZlcnksIGlkZW1wb3RlbmN5IGFuZCBib3VuZGVkIGNvbnZlcmdlbmNlIGFyZSBwcm92ZW4uIiwiVHJ1c3RlZCBDSSBhbmQgcGVybWFuZW50IGhvc3QtYmFja2VkIG9yY2hlc3RyYXRpb24gYXJlIG9wZXJhdGlvbmFsIHVuZGVyIGFjY2VwdGVkIGF1dGhvcml0eSBib3VuZGFyaWVzLiJdLCJlbGk1IjoiVGhpcyBsYXRlciBzdGVwIHdpbGwgYXV0b21hdGUgdGhlIGxvb3AgYXJvdW5kIHRoZSBwcm9ncmFtbWUgdG9vbC4iLCJlcG9jaHMiOlt7ImV2aWRlbmNlX3JlZiI6bnVsbCwiZ2F0ZXMiOlsiRzEiLCJHMiIsIkczIiwiRzQiXSwiaWQiOiJTMyIsImxvY2siOiJTMy1ERVNJR04tTE9DSy1QRU5ESU5HIiwibmFtZSI6IlMzIC0gUmVwb3NpdG9yeSBMb29wIE1hbmFnZXIiLCJwdXJwb3NlIjoiUmVwb3NpdG9yeSBsb29wIGFuZCB0cnVzdGVkIENJIGF1dG9tYXRpb24iLCJ0ZXJtaW5hbF9kaXNwb3NpdGlvbiI6bnVsbH1dLCJmaW5hbGl0eSI6eyJhdXRob3JpdHlfcmVmIjpudWxsLCJzdGF0ZSI6IkhFTEQifSwiaG9sZHMiOltdLCJpc3N1ZSI6MzYwLCJsaWZlY3ljbGUiOiJRVUVVRUQiLCJvYmplY3RpdmUiOiJCdWlsZCB0aGUgUmVwb3NpdG9yeSBMb29wIE1hbmFnZXIgYW5kIHRydXN0ZWQtQ0kgYXV0b21hdGlvbiBhcm91bmQgdGhlIEUzIHByaW1pdGl2ZS4iLCJvcmRlciI6Mywib3V0X29mX3Njb3BlIjpbIlM0IHRocm91Z2ggUzYgZXhlY3V0aW9uLiIsIlVuYXBwcm92ZWQgY29uc2VxdWVudGlhbCBsaXZlIG9yIHJlcG9zaXRvcnktcHJvdGVjdGlvbiBtdXRhdGlvbi4iXSwicHJfcmVnaXN0cnkiOltdLCJzY29wZSI6WyJSZXBvc2l0b3J5IExvb3AgTWFuYWdlciwgd29yayBncmFwaCwgbGVhc2VzL2ZlbmNlcywgZHVyYWJsZSByZWNvdmVyeSwgaWRlbXBvdGVuY3ksIGJvdW5kZWQgY29udmVyZ2VuY2UvdHdvLXJlcGFpciBzdG9wLCB0cnVzdGVkIENJIGFuZCBwZXJtYW5lbnQgaG9zdC1iYWNrZWQgb3JjaGVzdHJhdGlvbi4iXSwic3VtbWFyeSI6IkJ1aWxkIHRoZSBSZXBvc2l0b3J5IExvb3AgTWFuYWdlciBhbmQgdHJ1c3RlZC1DSSBhdXRvbWF0aW9uIGFyb3VuZCB0aGUgRTMgcHJpbWl0aXZlLiIsInRpdGxlIjoiUzMg4oCUIFJlcG9zaXRvcnkgTG9vcCBNYW5hZ2VyICsgdHJ1c3RlZCBDSSBsaXZlIGludGVncmF0aW9uIn0seyJib3VuZGFyaWVzIjpbIkxpdmUgbjhuIG9wZXJhdGlvbnMgcmVxdWlyZSBleHBsaWNpdCBhdXRob3JpdHkuIiwiVGhpcyBxdWV1ZWQgY2hpbGQgZG9lcyBub3Qgc3RhcnQgdW50aWwgaXRzIGRlcGVuZGVuY2llcyBhcmUgY29tcGxldGUgb3IgcmV0aXJlZC4iXSwiZGVsaXZlcmFibGVzIjpbIkV4YWN0LXBpbm5lZCBvZmZpY2lhbCBuOG4gU2tpbGxzLiIsIkFQSS1maXJzdCB3b3JrZmxvdyB0cmFuc3BvcnQuIiwiQ3JlZGVudGlhbC0gYW5kIGlkZW50aXR5LXNhZmUgYm91bmRhcmllcy4iLCJQYXVzZS1iZWZvcmUtZXhpdCBhbmQgSlNPTiBwcmltaXRpdmUgaW1wb3J0IHJlZ3Jlc3Npb25zIGZpeGVkIGFuZCBjb3ZlcmVkLiJdLCJkZXBlbmRlbmNpZXMiOlszNTgsMzU5LDM2MF0sImRvbmVfd2hlbiI6WyJPZmZpY2lhbCBuOG4gU2tpbGxzIGFyZSBleGFjdC1waW5uZWQgYW5kIEFQSS1maXJzdCB0cmFuc3BvcnQgaXMgcHJvdmVuLiIsIkNyZWRlbnRpYWwvaWRlbnRpdHkgc2FmZXR5LCBwYXVzZS1iZWZvcmUtZXhpdCBhbmQgSlNPTiBwcmltaXRpdmUgaW1wb3J0IHJlZ3Jlc3Npb25zIHBhc3MgdGhlaXIgcmVxdWlyZWQgZXZpZGVuY2UuIl0sImVsaTUiOiJUaGlzIGxhdGVyIHN0ZXAgd2lsbCBtYWtlIG44biBzdXBwb3J0IG9mZmljaWFsIGFuZCBzYWZlbHkgdHJhbnNwb3J0IHdvcmtmbG93cy4iLCJlcG9jaHMiOlt7ImV2aWRlbmNlX3JlZiI6bnVsbCwiZ2F0ZXMiOlsiRzEiLCJHMiIsIkczIiwiRzQiXSwiaWQiOiJTNCIsImxvY2siOiJTNC1ERVNJR04tTE9DSy1QRU5ESU5HIiwibmFtZSI6IlM0IC0gbjhuIHNraWxscyBhbmQgdHJhbnNwb3J0IiwicHVycG9zZSI6Ik9mZmljaWFsIG44biBza2lsbHMgYW5kIEFQSS1maXJzdCB0cmFuc3BvcnQiLCJ0ZXJtaW5hbF9kaXNwb3NpdGlvbiI6bnVsbH1dLCJmaW5hbGl0eSI6eyJhdXRob3JpdHlfcmVmIjpudWxsLCJzdGF0ZSI6IkhFTEQifSwiaG9sZHMiOltdLCJpc3N1ZSI6MzYxLCJsaWZlY3ljbGUiOiJRVUVVRUQiLCJvYmplY3RpdmUiOiJNb3ZlIG44biBzdXBwb3J0IHRvIG9mZmljaWFsIG44biBTa2lsbHMgYW5kIHNhZmUgQVBJLWZpcnN0IHdvcmtmbG93IHRyYW5zcG9ydC4iLCJvcmRlciI6NCwib3V0X29mX3Njb3BlIjpbIkN1c3RvbSBuOG4gTUNQIHJldml2YWwuIiwiTGl2ZSBuOG4gb3BlcmF0aW9ucyB3aXRob3V0IGV4cGxpY2l0IGF1dGhvcml0eS4iLCJTNSBhbmQgUzYgZXhlY3V0aW9uLiJdLCJwcl9yZWdpc3RyeSI6W10sInNjb3BlIjpbIk9mZmljaWFsIG44biBTa2lsbHMsIEFQSS1maXJzdCB0cmFuc3BvcnQsIGNyZWRlbnRpYWwvaWRlbnRpdHktc2FmZSBib3VuZGFyaWVzIGFuZCB0aGUgdHdvIHJlcG9ydGVkIHJlZ3Jlc3Npb25zLiJdLCJzdW1tYXJ5IjoiTW92ZSBuOG4gc3VwcG9ydCB0byBvZmZpY2lhbCBuOG4gU2tpbGxzIGFuZCBzYWZlIEFQSS1maXJzdCB3b3JrZmxvdyB0cmFuc3BvcnQuIiwidGl0bGUiOiJTNCDigJQgT2ZmaWNpYWwgbjhuIFNraWxscyArIEFQSS1maXJzdCB3b3JrZmxvdyB0cmFuc3BvcnQifSx7ImJvdW5kYXJpZXMiOlsiTm8gc2VjcmV0IHZhbHVlcyBpbiByZXBvLCBwcm9tcHRzLCBsb2dzIG9yIHB1YmxpYyBldmlkZW5jZS4iLCJDb25zZXF1ZW50aWFsIHByb3ZpZGVyIGFjdGlvbnMgcmVxdWlyZSBleHBsaWNpdCBhdXRob3JpdHkuIiwiVGhpcyBxdWV1ZWQgY2hpbGQgZG9lcyBub3Qgc3RhcnQgdW50aWwgaXRzIGRlcGVuZGVuY2llcyBhcmUgY29tcGxldGUgb3IgcmV0aXJlZC4iXSwiZGVsaXZlcmFibGVzIjpbIkV4dGVybmFsIGF1dGhvcml0eSBhbmQgc2VjcmV0LXJlZmVyZW5jZSBib3VuZGFyaWVzLiIsIlNlbnNpdGl2ZS1maWxlIGJvdW5kYXJpZXMuIiwiSG9zdGVkIG9wZXJhdGlvbnMsIGJhY2t1cCwgcm9sbGJhY2sgYW5kIGhlYWx0aC4iLCJQcml2YWN5LXNhZmUgdGVsZW1ldHJ5LiJdLCJkZXBlbmRlbmNpZXMiOlszNTgsMzU5LDM2MF0sImRvbmVfd2hlbiI6WyJFeHRlcm5hbCBhdXRob3JpdHksIHNlY3JldC1yZWZlcmVuY2UgYW5kIHNlbnNpdGl2ZS1maWxlIGJvdW5kYXJpZXMgYXJlIHByb3Zlbi4iLCJIb3N0ZWQgb3BlcmF0aW9ucywgYmFja3VwL3JvbGxiYWNrL2hlYWx0aCBhbmQgcHJpdmFjeS1zYWZlIHRlbGVtZXRyeSBtZWV0IGFjY2VwdGVkIGV2aWRlbmNlIHJlcXVpcmVtZW50cy4iXSwiZWxpNSI6IlRoaXMgbGF0ZXIgc3RlcCB3aWxsIGRlZmluZSB3aG8gbWF5IHRvdWNoIHByb3ZpZGVycywgc2VjcmV0cyBhbmQgaG9zdGVkIHN5c3RlbXMuIiwiZXBvY2hzIjpbeyJldmlkZW5jZV9yZWYiOm51bGwsImdhdGVzIjpbIkcxIiwiRzIiLCJHMyIsIkc0Il0sImlkIjoiUzUiLCJsb2NrIjoiUzUtREVTSUdOLUxPQ0stUEVORElORyIsIm5hbWUiOiJTNSAtIEV4dGVybmFsIGF1dGhvcml0eSBib3VuZGFyaWVzIiwicHVycG9zZSI6IkV4dGVybmFsIGF1dGhvcml0eSBhbmQgaG9zdGVkLW9wZXJhdGlvbiBib3VuZGFyaWVzIiwidGVybWluYWxfZGlzcG9zaXRpb24iOm51bGx9XSwiZmluYWxpdHkiOnsiYXV0aG9yaXR5X3JlZiI6bnVsbCwic3RhdGUiOiJIRUxEIn0sImhvbGRzIjpbXSwiaXNzdWUiOjM2MiwibGlmZWN5Y2xlIjoiUVVFVUVEIiwib2JqZWN0aXZlIjoiRXN0YWJsaXNoIGV4dGVybmFsIGF1dGhvcml0eSwgc2VjcmV0cywgcHJvdmlkZXIvZGVwbG95bWVudCBhbmQgaG9zdGVkLW9wZXJhdGlvbiBib3VuZGFyaWVzLiIsIm9yZGVyIjo1LCJvdXRfb2Zfc2NvcGUiOlsiU2VjcmV0IHZhbHVlcyBpbiByZXBvc2l0b3J5IGZpbGVzLCBwcm9tcHRzLCBsb2dzIG9yIHB1YmxpYyBldmlkZW5jZS4iLCJDb25zZXF1ZW50aWFsIHByb3ZpZGVyIGFjdGlvbnMgd2l0aG91dCBleHBsaWNpdCBhdXRob3JpdHkuIiwiUzYgZXhlY3V0aW9uLiJdLCJwcl9yZWdpc3RyeSI6W10sInNjb3BlIjpbIkV4dGVybmFsIGF1dGhvcml0eSwgc2VjcmV0IHJlZmVyZW5jZXMsIHNlbnNpdGl2ZSBmaWxlcywgaG9zdGVkIG9wZXJhdGlvbnMsIGJhY2t1cC9yb2xsYmFjay9oZWFsdGggYW5kIHByaXZhY3ktc2FmZSB0ZWxlbWV0cnkuIl0sInN1bW1hcnkiOiJFc3RhYmxpc2ggZXh0ZXJuYWwgYXV0aG9yaXR5LCBzZWNyZXRzLCBwcm92aWRlci9kZXBsb3ltZW50IGFuZCBob3N0ZWQtb3BlcmF0aW9uIGJvdW5kYXJpZXMuIiwidGl0bGUiOiJTNSDigJQgRXh0ZXJuYWwgYXV0aG9yaXR5LCBzZWNyZXRzICsgaG9zdGVkIG9wZXJhdGlvbnMifSx7ImJvdW5kYXJpZXMiOlsiUzYgcmVtYWlucyBsYXN0LiIsIkNvbnNlcXVlbnRpYWwgbGl2ZSBhY3Rpb25zIHJlcXVpcmUgc2VwYXJhdGUgYXV0aG9yaXR5LiJdLCJkZWxpdmVyYWJsZXMiOlsiRmluYWwgbmF0aXZlL2xpdmUgVUFULiIsIkxvb3AgTWFuYWdlciwgdHJ1c3RlZC1DSSBhbmQgbjhuIFVBVC4iLCJSZXNpZHVlIHZlcmlmaWNhdGlvbi4iLCJGaW5hbCB3aG9sZS1Ub29sa2l0IGFzc3VyYW5jZS4iXSwiZGVwZW5kZW5jaWVzIjpbMzU4LDM1OSwzNjAsMzYxLDM2Ml0sImRvbmVfd2hlbiI6WyJOYXRpdmUvbGl2ZSwgTG9vcCBNYW5hZ2VyLCB0cnVzdGVkLUNJIGFuZCBuOG4gVUFUIGFyZSBjb21wbGV0ZSB1bmRlciB0aGVpciBhdXRob3JpdGllcy4iLCJSZXNpZHVlIHZlcmlmaWNhdGlvbiBhbmQgZmluYWwgd2hvbGUtVG9vbGtpdCBhc3N1cmFuY2UgYXJlIGFjY2VwdGVkIGJ5IFdlYi4iXSwiZWxpNSI6IlRoaXMgZmluYWwgc3RlcCB3aWxsIHRlc3QgdGhlIHdob2xlIFRvb2xraXQgYWZ0ZXIgZXZlcnkgZWFybGllciBzdGVwIGlzIGRvbmUuIiwiZXBvY2hzIjpbeyJldmlkZW5jZV9yZWYiOm51bGwsImdhdGVzIjpbIkcxIiwiRzIiLCJHMyIsIkc0Il0sImlkIjoiUzYiLCJsb2NrIjoiUzYtREVTSUdOLUxPQ0stUEVORElORyIsIm5hbWUiOiJTNiAtIE5hdGl2ZSBVQVQgYW5kIGFzc3VyYW5jZSIsInB1cnBvc2UiOiJOYXRpdmUgVUFULCBjbGVhbnVwIGFuZCBmaW5hbCBhc3N1cmFuY2UiLCJ0ZXJtaW5hbF9kaXNwb3NpdGlvbiI6bnVsbH1dLCJmaW5hbGl0eSI6eyJhdXRob3JpdHlfcmVmIjpudWxsLCJzdGF0ZSI6IkhFTEQifSwiaG9sZHMiOltdLCJpc3N1ZSI6MzYzLCJsaWZlY3ljbGUiOiJRVUVVRUQiLCJvYmplY3RpdmUiOiJQZXJmb3JtIG5hdGl2ZS9saXZlIFVBVCwgcmVzaWR1ZSBjbGVhbnVwIGFuZCBmaW5hbCB3aG9sZS1Ub29sa2l0IGFzc3VyYW5jZS4iLCJvcmRlciI6Niwib3V0X29mX3Njb3BlIjpbIlN0YXJ0aW5nIGJlZm9yZSBTMSB0aHJvdWdoIFM1IG9ibGlnYXRpb25zIGFyZSB0ZXJtaW5hbCBhbmQgYWNjZXB0ZWQuIiwiQ29uc2VxdWVudGlhbCBsaXZlIGFjdGlvbnMgd2l0aG91dCBzZXBhcmF0ZSBhdXRob3JpdHkuIl0sInByX3JlZ2lzdHJ5IjpbXSwic2NvcGUiOlsiRmluYWwgbmF0aXZlL2xpdmUgVUFULCBMb29wIE1hbmFnZXIvdHJ1c3RlZC1DSS9uOG4gVUFULCByZXNpZHVlIHZlcmlmaWNhdGlvbiBhbmQgd2hvbGUtVG9vbGtpdCBhc3N1cmFuY2UuIl0sInN1bW1hcnkiOiJQZXJmb3JtIG5hdGl2ZS9saXZlIFVBVCwgcmVzaWR1ZSBjbGVhbnVwIGFuZCBmaW5hbCB3aG9sZS1Ub29sa2l0IGFzc3VyYW5jZS4iLCJ0aXRsZSI6IlM2IOKAlCBOYXRpdmUgVUFUICsgZmluYWwgd2hvbGUtVG9vbGtpdCBhc3N1cmFuY2UifV0sImNvbmN1cnJlbmN5X2F1dGhvcml0eSI6eyJhdXRob3JpdHlfZGlnZXN0IjpudWxsLCJhdXRob3JpdHlfcmVmIjpudWxsLCJtYXhfYWN0aXZlX2xhbmVzIjoxLCJtb2RlIjoiU0lOR0xFX0RFRkFVTFQiLCJwZXJtaXR0ZWRfY2hpbGRfaXNzdWVzIjpbXX0sImRlc2lnbl9sb2NrIjoiREwtUzItR0lUSFVCLVBST0dSQU0tU1VSRkFDRS1SRUNPVkVSWS0wMDMiLCJldmlkZW5jZV9yZWZzIjpbeyJpZCI6ImUzLWc0LWFjdGl2ZS10cmFuc2l0aW9uIiwia2luZCI6IldFQiIsInJlZmVyZW5jZSI6ImdpdGh1Yjppc3N1ZS1jb21tZW50OjM1Njo1NDU2MDc3NjQ3Iiwic3VtbWFyeSI6IkUzIEc0IGNvbnRyb2wtcGxhbmUgdHJhbnNpdGlvbiAtIFBSRVZJRVcgT05MWS4ifSx7ImlkIjoicmVwYWlyMS1jdXJyZW50Iiwia2luZCI6IldFQiIsInJlZmVyZW5jZSI6ImdpdGh1Yjppc3N1ZS1jb21tZW50OjM1OTo1NDUyMTM4MzkwIiwic3VtbWFyeSI6IkUzIEczIGNvbnZlcmdlbmNlIFJlcGFpciAxIGlzIGN1cnJlbnQgYW5kIGF3YWl0cyBXZWIgcmVjb25jaWxpYXRpb24uIn0seyJpZCI6InByaW9yLWc0LWFtZW5kIiwia2luZCI6IldFQiIsInJlZmVyZW5jZSI6ImdpdGh1Yjppc3N1ZS1jb21tZW50OjM1OTo1NDQ4ODE4MTQyIiwic3VtbWFyeSI6IlByaW9yIGlzb2xhdGVkIEUzIEc0IHJldHVybmVkIEFNRU5EIGFuZCByZXF1aXJlZCBjb252ZXJnZW5jZSBHMiByZS1lbnRyeS4ifSx7ImlkIjoiY29udmVyZ2VuY2UtZzItYWNjZXB0ZWQiLCJraW5kIjoiV0VCIiwicmVmZXJlbmNlIjoiZ2l0aHViOmlzc3VlLWNvbW1lbnQ6MzU5OjU0NDkwNzUzMDQiLCJzdW1tYXJ5IjoiRTMgY29udmVyZ2VuY2UgRzIgZGVzaWduIExvY2sgd2FzIGFjY2VwdGVkIGFuZCBHMyBhdXRob3Jpc2VkLiJ9LHsiaWQiOiJlMS1hY2NlcHRlZCIsImtpbmQiOiJXRUIiLCJyZWZlcmVuY2UiOiJnaXRodWI6aXNzdWUtY29tbWVudDozNjY6NTQyODc0MTIzMSIsInN1bW1hcnkiOiJTMiBFMSBDcmVhdGlvbiBHYXRlIHdhcyBXZWIgYWNjZXB0ZWQuIn0seyJpZCI6ImUyLWFjY2VwdGVkIiwia2luZCI6IldFQiIsInJlZmVyZW5jZSI6ImdpdGh1Yjppc3N1ZS1jb21tZW50OjM2Njo1NDM3MjY2MTU3Iiwic3VtbWFyeSI6IlMyIEUyIFByb2R1Y3QgUG9ydGZvbGlvIHdhcyBXZWIgYWNjZXB0ZWQuIn0seyJpZCI6InMxLWFjY2VwdGVkIiwia2luZCI6IldFQiIsInJlZmVyZW5jZSI6ImdpdGh1Yjppc3N1ZS1jb21tZW50OjM1ODo1NDI2OTQ4Mzk0Iiwic3VtbWFyeSI6IlMxIHdhcyB0ZXJtaW5hbCwgY2Fub25pY2FsLCBhbmQgYWNjZXB0ZWQuIn0seyJpZCI6InByZWRlY2Vzc29yLWNvdmVyYWdlIiwia2luZCI6IldFQiIsInJlZmVyZW5jZSI6ImdpdGh1Yjppc3N1ZS1jb21tZW50OjM1OTo1NDM3ODI3MDMwIiwic3VtbWFyeSI6IlByZWRlY2Vzc29yIGNvdmVyYWdlIGlzIGV4YWN0bHkgNDUgaXNzdWVzLCA4NCBjcml0ZXJpYSwgYW5kIHplcm8gdW5tYXBwZWQuIn0seyJpZCI6InJlcGFpci1oZWFkIiwia2luZCI6IkNPTU1JVCIsInJlZmVyZW5jZSI6ImdpdDpjb21taXQ6NDQ2NDcxZTYyNDhiZjhiYzY1NDBkNGEwM2FhMmEwZTFhYjYyNWYzZCIsInN1bW1hcnkiOiJFeGFjdCBSZXBhaXIgMSBjYW5kaWRhdGUgY29tbWl0LiJ9LHsiaWQiOiJyZXBhaXItY2hlY2tzIiwia2luZCI6IkNIRUNLIiwicmVmZXJlbmNlIjoiZ2l0aHViOmNoZWNrczo0NDY0NzFlNjI0OGJmOGJjNjU0MGQ0YTAzYWEyYTBlMWFiNjI1ZjNkIiwic3VtbWFyeSI6IkV4YWN0LWhlYWQgdmFsaWRhdGlvbiBhbmQgQ29kZVFMIHBhc3NlZC4ifSx7ImlkIjoid2ViXzc3MDRjYTBkODcyNTZiNDI3ZjYzIiwia2luZCI6IldFQiIsInJlZmVyZW5jZSI6ImdpdGh1Yjppc3N1ZS1jb21tZW50OjM1OTo1NDYyOTg1MDcxIiwic3VtbWFyeSI6IldlYi1jb250cm9sbGVkIEUzIGFyY2hpdGVjdHVyZSBhbmQgZXhhY3QtY2FuZGlkYXRlIGFkbWlzc2lvbiBhdXRob3JpdHkuIn0seyJpZCI6ImUzLWczLWRvZ2Zvb2QtYWNjZXB0ZWQiLCJraW5kIjoiV0VCIiwicmVmZXJlbmNlIjoiZ2l0aHViOmlzc3VlLWNvbW1lbnQ6MzU5OjU0NjY5MTI1NjYiLCJzdW1tYXJ5IjoiV2ViIGFjY2VwdGVkIEUzIEczIGRvZ2Zvb2QgYW5kIGF1dGhvcmlzZWQgdGhlIGZyZXNoIEc0IHRyYW5zaXRpb24gcHJldmlldy4ifV0sImV4dGVuc2lvbnMiOltdLCJoaXN0b3JpY2FsX3RyYW5zaXRpb25zIjpbeyJjaGlsZF9pc3N1ZSI6MzU5LCJkaXNwb3NpdGlvbiI6IkFNRU5EIiwiZXBvY2hfaWQiOiJFMyIsImV2aWRlbmNlX3JlZiI6InByaW9yLWc0LWFtZW5kIiwiZ2F0ZSI6Ikc0IiwiaWQiOiJlMy1wcmlvci1nNC1hbWVuZCJ9LHsiY2hpbGRfaXNzdWUiOjM1OSwiZGlzcG9zaXRpb24iOiJBQ0NFUFRFRCIsImVwb2NoX2lkIjoiRTMiLCJldmlkZW5jZV9yZWYiOiJjb252ZXJnZW5jZS1nMi1hY2NlcHRlZCIsImdhdGUiOiJHMiIsImlkIjoiZTMtY29udmVyZ2VuY2UtZzItYWNjZXB0ZWQifSx7ImNoaWxkX2lzc3VlIjozNTksImRpc3Bvc2l0aW9uIjoiQUNDRVBURUQiLCJlcG9jaF9pZCI6IkUzIiwiZXZpZGVuY2VfcmVmIjoiZTMtZzMtZG9nZm9vZC1hY2NlcHRlZCIsImdhdGUiOiJHMyIsImlkIjoiZTMtZzMtZG9nZm9vZC1hY2NlcHRlZCJ9XSwicGFyZW50Ijp7ImdvYWwiOiJEZWxpdmVyIHRoZSBzaXgtc3RhZ2UgVG9vbGtpdCBwcm9ncmFtbWUgdGhyb3VnaCB0cnV0aGZ1bCwgZGV0ZXJtaW5pc3RpYywgc291cmNlLXRyYWNlYWJsZSBwcm9ncmFtbWUgdmlld3MuIiwiaXNzdWUiOjI0MCwidGl0bGUiOiJbIFBBUkVOVCBUSFJFQUQgXSBBSSBBZ2VudCBUb29sa2l0IOKAlCBSb2xsaW5nIFdvcmsgUXVldWUifSwicHJlZGVjZXNzb3JfY29udHJhY3RfZGlnZXN0IjoiNmVhOWEzNTM5NzM3Njk5NTczMGMwNDJmN2NkOTE1MDg0MzQ4YzQyM2VhZTc2ZGIwNThhNDgwYWM5YzllMjI3NiIsInBycyI6W3siY2hhbmdlZF9zdXJmYWNlcyI6WyJHaXRIdWIgcHJvZ3JhbW1lIHJlY29uY2lsZXIgcnVudGltZSBhbmQgcG9saWN5LiIsIlByb2dyYW1tZSBzdXJmYWNlIGFuZCBwcmVkZWNlc3NvciBjb250cmFjdHMuIiwiRm9jdXNlZCByZWNvbmNpbGlhdGlvbiBhbmQgYnJpZGdlIHRlc3RzLiIsIkFsaWduZWQgbmF0aXZlIHBsdWdpbiBhbmQgYnJpZGdlIHZlcnNpb24gc3VyZmFjZXMuIl0sImNoaWxkX2lzc3VlIjozNTksImRlc2lnbl9jb25zdHJhaW50cyI6WyJSb2xlIHJlbWFpbnMgSU5URVJNRURJQVRFIGFuZCBjb21wbGV0ZXNfY2hpbGQgcmVtYWlucyBmYWxzZS4iLCJQUiByZW1haW5zIGRyYWZ0LiIsIk5vIGZpbmFsaXR5IG9wZXJhdGlvbiBpcyBhdXRob3Jpc2VkIGJ5IHRoaXMgcmVjb25jaWxpYXRpb24uIl0sImVsaTUiOiJUaGUgcmVwYWlyIGFuZCBkb2dmb29kIGNvcnJlY3Rpb24gYXJlIGFjY2VwdGVkLCBhbmQgdGhlIGZpbmFsIGluZGVwZW5kZW50IEUzIHJldmlldyBnYXRlIGlzIGFjdGl2ZSB3aXRob3V0IGEgcmVzdWx0LiIsImV2aWRlbmNlX3JlZnMiOltdLCJudW1iZXIiOjM2Niwib3V0X29mX3Njb3BlIjpbIkc0IHJlc3VsdCBvciBFMyBhY2NlcHRhbmNlIGJlZm9yZSBzZXBhcmF0ZSBXZWIgYXV0aG9yaXR5LiIsIlJlYWR5LCBtZXJnZSwgZmluYWxpdHksIEU0IGFuZCBTMyB0aHJvdWdoIFM2IGV4ZWN1dGlvbi4iLCJQcm92aWRlciwgZGVwbG95bWVudCwgY3JlZGVudGlhbCBhbmQgbGl2ZSBuOG4gb3BlcmF0aW9ucy4iXSwicHVycG9zZSI6IkltcGxlbWVudCBhbmQgcHJvdmUgdGhlIGRldGVybWluaXN0aWMgR2l0SHViIHByb2dyYW1tZSByZWNvbmNpbGVyIHByb2R1Y3QgZm9yIFMyIEUzLiIsInNjb3BlIjpbIkNhbm9uaWNhbCBwYXJlbnQsIGNoaWxkIGFuZCBQUiB2aWV3cy4iLCJNYW5hZ2VkIGxpZmVjeWNsZSBsYWJlbHMgYW5kIHR5cGVkIGV2ZW50cy4iLCJFeGlzdGluZy1pc3N1ZSBzdWItaXNzdWUgYW5kIGJsb2NrZWQtYnkgcmVsYXRpb25zaGlwcy4iLCJQcmV2aWV3LCBleHBsaWNpdCBhcHBseSwgcmVhZGJhY2sgdmVyaWZpY2F0aW9uIGFuZCBleGFjdCByZXJ1biB6ZXJvIGRlbHRhLiJdLCJzdW1tYXJ5IjoiRTMgUmVwYWlyLTIgaW1wbGVtZW50YXRpb24sIHY1IG1pZ3JhdGlvbi9yZWFkYmFjay96ZXJvLWRlbHRhIGFuZCBkb2dmb29kIFVYIGNvcnJlY3Rpb24gYXJlIGFjaGlldmVkOyBmcmVzaCBHNCBpcyBub3cgYWN0aXZlIHdpdGggbm8gcmVzdWx0LiIsInZhbGlkYXRpb25fcmVxdWlyZW1lbnRzIjpbIlJlcGFpci0yIGZvY3VzZWQgdGVzdHMgcGFzc2VkIDI0LzI0LiIsIlJlbGV2YW50IHJlY29uY2lsZXIgc3VpdGUgcGFzc2VkIDI1NS8yNTUuIiwiVG9vbGtpdCB2YWxpZGF0aW9uIGFuZCBhdWRpdHMgcGFzc2VkLiIsIkV4YWN0LWhlYWQgVmFsaWRhdGUgcGFzc2VkLiIsIkV4YWN0LWhlYWQgVmFsaWRhdGUgdG9vbGtpdCBwYXNzZWQuIiwiQ29kZVFMIGFuZCBsYW5ndWFnZSBhbmFseXNlcyBwYXNzZWQuIiwiRHluYW1pYyBHSEFTIHVuc3VwcG9ydGVkLW1vZGVsIGZhaWx1cmUgaXMgZXh0ZXJuYWwvbm9uLWNhbmRpZGF0ZSBldmlkZW5jZS4iLCJEdXJhYmxlIG9yaWdpbmFsIG1pZ3JhdGlvbiBwcmV2aWV3IGFuZCByZWNlaXB0IHdlcmUgcmVhZCBiYWNrLiIsIkV4YWN0bHkgb25lIGF1dGhvcmlzZWQgdjUgbWlncmF0aW9uIEFwcGx5IGNvbXBsZXRlZC4iLCJNaWdyYXRpb24gZXZlbnQ6IDg3ODUxYjM2ZTBmNTRkZDk2OWFjMWI4NWU0OWUyZjE1OWFlZWZlZTE0OTc4NjFmMjBlMmZkNDViMDIxMjhlNjYuIiwiSW1tZWRpYXRlIG1pZ3JhdGlvbiByZXJ1bjogUFJPR1JBTU1FX1pFUk9fREVMVEEgLyBtdXRhdGlvbl9jb3VudD0wLiIsIkRvZ2Zvb2QgVVggY29ycmVjdGlvbiBhY2NlcHRlZCBieSBXZWIgdW5kZXIgYXV0aG9yaXR5IGNvbW1lbnQgNTQ2NjkxMjU2Ni4iLCJGcmVzaCBHNDogQUNUSVZFIC8gTk8gUkVTVUxULiJdfV0sInJlcG9zaXRvcnkiOiJ3ZWlqdW5zd2ovYWktYWdlbnQtdG9vbGtpdCIsInNjaGVtYSI6InRvb2xraXQuZ2l0aHViLXByb2dyYW0uc3RhdGUudjUifX0 -->\n<!-- AI-AGENT-TOOLKIT:GITHUB-PROGRAM-PARENT:END -->";
const CHILD_BODY = "<!-- AI-AGENT-TOOLKIT:GITHUB-PROGRAM-CHILD:BEGIN v5 -->\n# S2 — Productize retained skills + native host adapters\n\n## Summary\nE1 and E2 are accepted; E3 Repair-2 implementation, v5 migration/readback/zero-delta and dogfood UX correction are achieved; fresh G4 is now active with no result.\n\n## Operating contract\n| Field | Value |\n| --- | --- |\n| Parent | #240 |\n| Lane | child-359 |\n| Lifecycle | CURRENT |\n| Epoch | E3 |\n| Gate | G4 |\n| Gate state | ACTIVE |\n| Lock | DL-S2-GITHUB-PROGRAM-CONVERGENCE-002 |\n| Finality | HELD |\n\n## Objective\nProductise retained skills, complete the GitHub programme reconciler, then finish truthful native host adapters.\n\n## Deliverables\n- Retained-skill productisation.\n- GitHub programme reconciler v5.\n- Future E4 truthful native adapters.\n\n## Done when\n- E1 and E2 remain accepted with retained evidence.\n- E3 Repair-2, v5 migration/readback/zero-delta, canonical-data UX correction, fresh G4 and Web acceptance are complete.\n- E4 truthful native adapters are complete and Web records S2 finality.\n\n## Scope\n- Retained-skill productisation, GitHub programme reconciler v5 and future E4 truthful native adapters.\n- Fresh E3 G4 transition and exact-candidate validation.\n\n## Out of scope\n- G4 result or E3 acceptance before separate Web authority.\n- Ready, merge, finality, E4 execution and S3 through S6 progression.\n\n## Progress\n- E1: ACCEPTED\n- E2: ACCEPTED\n- E3: G4 ACTIVE\n- E4: PENDING\n\n## Achieved\n- E1 ACCEPTED\n- E2 ACCEPTED\n- E3 G4 AMEND\n- E3 G2 ACCEPTED\n- E3 G3 ACCEPTED\n\n## Remaining\n- E3 G4\n- E4 G1\n- E4 G2\n- E4 G3\n- E4 G4\n- Web finality disposition\n\n## Epochs / Locks\n| Epoch | Lock | State | Purpose |\n| --- | --- | --- | --- |\n| E1 | DL-S2-CREATION-GATE-003 | ACCEPTED | Creation and admission gate |\n| E2 | DL-S2-PRODUCT-PORTFOLIO-015 | ACCEPTED | Retained product portfolio |\n| E3 | DL-S2-GITHUB-PROGRAM-CONVERGENCE-002 | ACTIVE | Managed GitHub programme reconciliation |\n| E4 | DL-S2-NATIVE-ADAPTERS-002 | PENDING | Truthful native host adapters |\n\n## PR registry\n| PR | Status | Role | Completes Child |\n| --- | --- | --- | --- |\n| #366 | ACTIVE | INTERMEDIATE | No |\n\n## Holds\nNone\n\n## Boundaries\n- Web owns fresh G4 disposition, E3 acceptance, Ready, merge and finality.\n- Fresh G4 is active with no result yet.\n- E4 and S3 through S6 do not begin in this transition.\n\n## Next action\nComplete E3 G4 without advancing finality.\n\n## ELI5\nThe programme tool is repaired and its final independent E3 review gate is now active, but no result or acceptance exists yet.\n\n## Additional context\nNone\n\n<!-- AI-AGENT-TOOLKIT:GITHUB-PROGRAM-PROJECTION v1 eyJjYW5vbmljYWxfZGlnZXN0IjoiYTA5ZmRhZmE2Yjc3YWQ4NTYyNDI5OGNlZWE0ODhhNWMzNDJkMDBhMDcwMDIxOGRlNjJiYTIyNzZlZDA1MDI4MCIsImV4dGVuc2lvbl9kaWdlc3QiOiI0ZjUzY2RhMThjMmJhYTBjMDM1NGJiNWY5YTNlY2JlNWVkMTJhYjRkOGUxMWJhODczYzJmMTExNjEyMDJiOTQ1Iiwia2luZCI6ImNoaWxkIiwibnVtYmVyIjozNTksInBhcmVudF9pc3N1ZSI6MjQwLCJwcm9qZWN0aW9uX2RpZ2VzdCI6IjQ3MmFlMDkxZmY2NzRmN2IxMzk4OTg0NGE5MjBiZmVlYjliYjE5ZWU2NWY0ZWYyNWFmZjQ1YzgyNDQ0MTQ4ZjkiLCJyZXBvc2l0b3J5Ijoid2VpanVuc3dqL2FpLWFnZW50LXRvb2xraXQiLCJzY2hlbWEiOiJ0b29sa2l0LmdpdGh1Yi1wcm9ncmFtLnByb2plY3Rpb24udjEifQ -->\n<!-- AI-AGENT-TOOLKIT:GITHUB-PROGRAM-CHILD:END -->";
const PR379_REVIEW_BODY = "## WEB EXACT-HEAD G3 BLOCKED ADJUDICATION / REPAIR-1 AUTHORITY\n\nExact reviewed head: `d3587fb69f0043d74936c116168a17247174ba07` / tree `1cf1bfbccee02b757040350c872bf18ad8056071` against canonical main `c72028c63cc09dd07d3e522692065448b6b7dbb6`.\n\nWeb accepts the G3 implementation structurally but does not accept it as G3-complete because both hosted Validate jobs fail.\n\nThe two failures are adjudicated as same-root test harness/fixture defects only:\n1. real receipt-store tamper test reopens/reads the deliberately corrupted store outside the intended fail-closed assertion boundary;\n2. real SQLite recovery fixture references `harnessA.scope.scope_digest` instead of canonical `harnessA.scope.grant.scope_digest`.\n\nNo runtime, G1 or G2 defect is presently established.\n\nControlling Repair-1 authority: #359 comment `5578743909`.\nParent mirror: #240 comment `5578745835`.\n\nRepair 1 may change only the receipt test, programme-bootstrap-recovery test, then a bootstrap-only repin. No other candidate mutation is authorised. Repair 2, G4, Ready, merge and Programme Apply remain unauthorised pending Web adjudication.";
const PR379_COMMENT_BODIES = Object.freeze({"issue-240-5580975069":"## WEB / S2 E3 RECOVERY G2 ACCEPTED — G3 RECOVERY IMPLEMENTATION CURRENT\n\nRUN=2026-09-08-toolkit-s2-e3-v5-projection-bootstrap-recovery-g2-adjudication\nCHILD=359\nRECOVERY_ROOT=E3-V5-PROGRAMME-PROJECTION-BOOTSTRAP-RECOVERY-001\nLOCK=DL-S2-E3-V5-PROJECTION-BOOTSTRAP-RECOVERY-001\nCONTROLLING_CHILD_AUTHORITY=#359/5580972753\n\nMAIN=c72028c63cc09dd07d3e522692065448b6b7dbb6\nMAIN_TREE=1b7d3fe13251ae91b93498a87248b85c15268c26\nPARENT_RECONCILIATION_INCOMPLETE=YES_PROJECTION_STALE\n\nWeb accepts the recovery G2 contract without another worker rerun. The G2 worker correctly found that GitHub issue PATCH has no documented provider-enforced conditional-write precondition, so the recovery must not claim CAS.\n\nAccepted recovery-only write boundary for the later separately authorised Apply:\n`WRITE_SAFETY_MODE=WEB_EXCLUSIVE_SINGLE_WRITER_RECOVERY_WINDOW`.\n\nDuring that eventual window Web/owner reserves #359/#240 bodies against all authorised competing Toolkit/manual writes; the designated writer performs fresh rebind, serial #359-first/#240-last writes, exact readback and immediate zero delta. The small non-cooperating external GET-to-PATCH race is explicit residual risk accepted only for this two-body control-plane recovery, not described as CAS and not a general product guarantee.\n\nThe G2 nine-path lock is accepted unchanged otherwise. No version bump: Toolkit remains 2.10.8. Source commit S owns eight recovery core paths; bootstrap commit B owns only `.github/ai-agent-toolkit-programme.json`. Receipt runtime/schema, historical-receipt work, v4 migration, managed events, provider clients, workflows, plugin/local-bridge/version churn and all other paths remain forbidden.\n\nRecovery G3 is now authorised from exact canonical main. G3 may create/push a fresh branch and Draft recovery PR and publish only S then B under the accepted scope. It may not mutate #240/#359 bodies, perform Programme Apply, mutate #379, launch normal E3, run G4, mark Ready, merge or advance finality.\n\nG3_RECOVERY_IMPLEMENTATION_AUTHORISED=YES\nPROGRAMME_APPLY_AUTHORISED=NO\nG4_AUTHORISED=NO_PENDING_EXACT_HEAD_WEB_ADJUDICATION\nREADY_AUTHORISED=NO\nMERGE_AUTHORISED=NO\nNORMAL_PROGRAMME_PROGRESS_AUTHORISED=NO\n\nPR #379 remains OPEN/DRAFT/UNMERGED/FROZEN. Old E3-003 remains terminal non-convergent at 2/2 with no Repair 3. Parked root `E3-HISTORICAL-RECEIPT-CI-PROOF-BOUNDARY-SIMPLIFICATION-004` remains NOT_LAUNCHED.\n\nNEXT_ACTION=Recovery-only G3 under #359 controlling authority.\nSECRET_CLASSIFICATION=none\n\nRefs #359\nRefs #379","issue-240-5580534575":"## WEB / S2 E3 RECOVERY G1 ACCEPTED — MINIMISED G2 CURRENT\n\nRUN=2026-09-08-toolkit-s2-e3-v5-projection-bootstrap-g1-adjudication\nCHILD=359\nRECOVERY_ROOT=E3-V5-PROGRAMME-PROJECTION-BOOTSTRAP-RECOVERY-001\nG1_RESULT=ACCEPTED_WITH_WEB_SCOPE_REFINEMENT\nG2_LOCK=DL-S2-E3-V5-PROJECTION-BOOTSTRAP-RECOVERY-001\nG2_CURRENT=YES_READ_ONLY\n\nMAIN=c72028c63cc09dd07d3e522692065448b6b7dbb6\nMAIN_TREE=1b7d3fe13251ae91b93498a87248b85c15268c26\nPR379_HEAD=adca2ffec8322eb57afcd9f9fdc67210503ebcf1\nPR379_TREE=2c712aa9c7c6e66a89bdd9d033acece5415fd575\nPARENT_RECONCILIATION_INCOMPLETE=YES_PROJECTION_STALE\n\nParent mirror of the controlling Child #359 Web G1 adjudication. Web accepts Option B: a fresh minimal recovery bootstrap from canonical main is the correct architecture. The live/candidate evidence confirms three real v5 expressivity gaps: held CURRENT cannot currently have zero normal active lanes, the PR registry lacks RETAINED, and historical state lacks typed NON_CONVERGENT/repair-budget semantics.\n\nScope refinement is binding: the G1 worker's 32-path proposal is not a G3 allowlist. Recovery G2 must minimise the source surface and justify every allowed path. Package/plugin/local-bridge/version-alignment and broad docs/audit churn are presumptively excluded unless a canonical rule proves them strictly necessary. The #379 v5 surface contract must not be copied wholesale because historical-receipt `readReceiptById` and v4 migration remain outside this recovery. No receipt runtime/schema change, managed-event change, provider client, workflow/fetch-depth change, or caller-supplied full desired state is allowed.\n\nThe future mechanism must render only the deterministic #240/#359 recovery state, bind complete evidence, plan exactly #359-first/#240-last body operations, fail closed on movement/partial writes, perform exact readback + zero delta, use the existing receipt subsystem unchanged, and—if implementation is later authorised—publish source S then bootstrap-only B. Any later merge must preserve S; merge-commit is available in repository settings.\n\nPR #379 remains frozen OPEN/DRAFT/UNMERGED. Old E3-003 remains terminal non-convergent at repair budget 2/2 with no Repair 3. Parked root `E3-HISTORICAL-RECEIPT-CI-PROOF-BOUNDARY-SIMPLIFICATION-004` remains NOT_LAUNCHED.\n\nG3_RECOVERY_IMPLEMENTATION_AUTHORISED=NO_PENDING_G2\nPARKED_ROOT_G2_AUTHORISED=NO\nPROGRAMME_APPLY_AUTHORISED=NO\nG4_AUTHORISED=NO\nREADY_AUTHORISED=NO\nMERGE_AUTHORISED=NO\nNORMAL_PROGRAMME_PROGRESS_AUTHORISED=NO\n\nNEXT_ACTION=Fresh read-only recovery G2 Design Lock, then Web adjudication.\nSECRET_CLASSIFICATION=none\n\nRefs #359\nRefs #379","issue-359-5580972753":"## WEB / RECOVERY G2 CAS ADJUDICATION — G2 ACCEPTED WITH SINGLE-WRITER AMENDMENT; G3 AUTHORISED\n\nRUN=2026-09-08-toolkit-s2-e3-v5-projection-bootstrap-recovery-g2-adjudication\nRECOVERY_ROOT=E3-V5-PROGRAMME-PROJECTION-BOOTSTRAP-RECOVERY-001\nLOCK=DL-S2-E3-V5-PROJECTION-BOOTSTRAP-RECOVERY-001\nG2_WORKER_RESULT=GATE_REENTRY_REQUIRED\nWEB_G2_DISPOSITION=ACCEPTED_WITH_EXPLICIT_WRITE_TRUST_BOUNDARY_AMENDMENT\nG2_RERUN_REQUIRED=NO\n\nMAIN=c72028c63cc09dd07d3e522692065448b6b7dbb6\nMAIN_TREE=1b7d3fe13251ae91b93498a87248b85c15268c26\nPR379_HEAD=adca2ffec8322eb57afcd9f9fdc67210503ebcf1\nPR379_STATE=OPEN_DRAFT_UNMERGED_FROZEN\nPARENT_RECONCILIATION_INCOMPLETE=YES_PROJECTION_STALE\n\nWeb independently confirms the worker's narrow blocker: GitHub REST conditional requests are generally unsupported for unsafe methods unless a specific endpoint documents otherwise, and the issue-body PATCH endpoint exposes no ETag/expected-revision write precondition. Therefore prewrite rebind + PATCH + readback MUST NOT be called provider CAS.\n\nWeb resolves this as a recovery-only trust-boundary decision rather than rerunning G2:\n\nWRITE_SAFETY_MODE=WEB_EXCLUSIVE_SINGLE_WRITER_RECOVERY_WINDOW\nPROVIDER_CAS_CLAIM=FORBIDDEN\nRESIDUAL_EXTERNAL_RACE=EXPLICITLY_ACCEPTED_FOR_THIS_RECOVERY_ONLY\n\nThe eventual Programme Apply window, if separately authorised after merge/preview, is valid only while all of these hold:\n1. Web/owner reserves issue bodies #359 and #240 exclusively to the single designated recovery writer for the duration of the two ordered body writes and readback.\n2. No other authorised Toolkit worker, controller lane, automation, manual owner edit, or reconciliation action may mutate #359/#240 bodies during that window.\n3. Writes are strictly serial: fresh complete evidence/rebind -> #359 write -> exact #359 readback -> fresh complete rebind of all external facts -> #240 write -> full readback -> immediate zero delta.\n4. Any observed movement, authority change, body difference, label/native relationship movement, PR movement, partial-state mismatch, or inability to maintain the reservation fails closed to Web.\n5. The existing A1/receipt machinery binds operation identity and serialisation but MUST NOT be represented as provider CAS. Do not use a receipt/operation label that asserts CAS or conditional-provider enforcement when none exists. Bind the accepted `WEB_EXCLUSIVE_SINGLE_WRITER_RECOVERY_WINDOW` safety mode in the recovery decision/preview/operation digest using existing generic receipt admission semantics.\n6. The residual risk is the narrow non-cooperating external GET-to-PATCH race which GitHub cannot atomically exclude. Web accepts that residual risk only because this is a one-time two-body governance-projection recovery with exact deterministic target bytes, no repository/source/PR/label/native/finality mutation, serial operation, and full immediate readback. This is NOT a general claim that GitHub issue-body writes are race-free and creates no precedent to describe ordinary issue PATCH as CAS.\n7. If G3 discovers the unchanged canonical receipt API cannot truthfully bind this operation without modifying receipt source/schema or falsely labelling it CAS, stop with `GATE_REENTRY_REQUIRED`; receipt changes remain outside scope.\n\nThe remainder of the G2 contract is accepted. The final implementation scope is exactly nine paths, with no version bump:\n\nSOURCE COMMIT S — exactly eight paths:\n- repo/contracts/github-program-reconciler/controller-bootstrap-v1.schema.json\n- repo/contracts/github-program-reconciler/programme-state-v5.schema.json\n- repo/contracts/github-program-reconciler/programme-surface-contract-v5.json\n- repo/contracts/github-program-reconciler/projection-bootstrap-recovery-decision-v1.schema.json\n- repo/contracts/github-program-reconciler/projection-bootstrap-recovery-evidence-v1.schema.json\n- repo/scripts/toolkit-github-program-state-v5.cjs\n- repo/scripts/toolkit-github-governance-review-reconciler.cjs\n- repo/tests/toolkit-github-programme-projection-bootstrap-recovery-v5.test.cjs\n\nBOOTSTRAP COMMIT B — exactly one path:\n- .github/ai-agent-toolkit-programme.json\n\nALLOWED_PATH_COUNT=9\nVERSION_BUMP_REQUIRED=NO\nTOOLKIT_VERSION_REMAINS=2.10.8\n\nAll other paths are forbidden, including receipt runtime/schema, historical `readReceiptById`, v4/migration/managed-event surfaces, plugin/local-bridge/version alignment, skill/docs/audit churn, provider client code and `.github/workflows/**`.\n\nG3 publication contract:\n- fresh branch from exact main c72028c63cc09dd07d3e522692065448b6b7dbb6;\n- S direct child of main, exactly the eight source/contract/test paths;\n- B direct child of S, bootstrap-only;\n- hosted bootstrap proof uses checked-in bootstrap + workspace contract bytes, never parent Git-object lookup;\n- create/retain a Draft recovery PR;\n- run focused tests, existing affected receipt/reconciler suites, validate-toolkit, git diff --check and applicable audits;\n- hosted Validate, Validate toolkit and CodeQL/language analyses must be green before G4 admission;\n- no mutation of #240/#359 bodies during G3;\n- no Programme Apply, G4, Ready, merge or finality in G3.\n\nG3_RECOVERY_IMPLEMENTATION_AUTHORISED=YES\nPROGRAMME_APPLY_AUTHORISED=NO\nG4_AUTHORISED=NO_PENDING_EXACT_HEAD_WEB_ADJUDICATION\nREADY_AUTHORISED=NO\nMERGE_AUTHORISED=NO\nPARKED_ROOT_G2_AUTHORISED=NO\nNORMAL_PROGRAMME_PROGRESS_AUTHORISED=NO\n\nOLD_ROOT=E3-CANONICAL-HISTORICAL-RECEIPT-RESOLUTION-003\nOLD_ROOT_DISPOSITION=TERMINAL_NON_CONVERGENT\nREPAIR_BUDGET=2/2_CONSUMED\nREPAIR3_AUTHORISED=NO\n\nPARKED_ROOT=E3-HISTORICAL-RECEIPT-CI-PROOF-BOUNDARY-SIMPLIFICATION-004\nPARKED_ROOT_STATUS=NOT_LAUNCHED\n\nNEXT_ACTION=Run recovery-only G3 on the exact nine-path lock and return exact S/B/PR/validation evidence to Web.\nSECRET_CLASSIFICATION=none\n\nRefs #240\nRefs #379","issue-359-5580530088":"## WEB / RECOVERY G1 ACCEPTED — MINIMISED G2 DESIGN LOCK CURRENT\n\nRUN=2026-09-08-toolkit-s2-e3-v5-projection-bootstrap-g1-adjudication\nRECOVERY_ROOT=E3-V5-PROGRAMME-PROJECTION-BOOTSTRAP-RECOVERY-001\nG1_RESULT=ACCEPTED_WITH_WEB_SCOPE_REFINEMENT\nG2_LOCK=DL-S2-E3-V5-PROJECTION-BOOTSTRAP-RECOVERY-001\nG2_CURRENT=YES_READ_ONLY\n\nMAIN=c72028c63cc09dd07d3e522692065448b6b7dbb6\nMAIN_TREE=1b7d3fe13251ae91b93498a87248b85c15268c26\nPR379_HEAD=adca2ffec8322eb57afcd9f9fdc67210503ebcf1\nPR379_TREE=2c712aa9c7c6e66a89bdd9d033acece5415fd575\nPR379_DISPOSITION=RETAIN_OPEN_DRAFT_UNMERGED_FROZEN\nPARENT_RECONCILIATION_INCOMPLETE=YES_PROJECTION_STALE\n\nWeb accepts the G1 architectural conclusion: use a fresh minimal recovery bootstrap PR from canonical main. Existing trusted v3/A1/A2/receipt primitives are reusable, but cannot alone parse/render the live v5 state or express the required held/retained/non-convergent semantics. A one-off external renderer and wholesale #379 reuse remain rejected.\n\nWeb independently confirmed the material candidate-v5 gaps: CURRENT children are currently forced to have an active lane; PR registry states do not include RETAINED; historical transition dispositions do not include NON_CONVERGENT. These are real schema/runtime expressivity gaps, not merely stale Markdown.\n\n### Web scope refinement\n\nThe G1 packet's proposed 32-path implementation allowlist is NOT accepted as the G3 allowlist. G2 must derive the smallest exact recovery-core path set and justify every path.\n\nPresumptively OUT unless G2 proves an existing canonical validation/publication rule makes a change strictly unavoidable:\n- package/plugin/local-bridge version bump or alignment churn;\n- `.claude-plugin/**`, `.codex-plugin/**`, local-bridge version surfaces, agent-control/setup/delegation version constants;\n- published-surface/Safety Matrix/Skill Creation baseline churn;\n- broad skill documentation rewrites;\n- `validate-toolkit.cjs` changes beyond demonstrably necessary contract registration.\n\nThe #379 `programme-surface-contract-v5.json` must NOT be reused wholesale: it includes parked historical-receipt and migration semantics that are outside this recovery. Recovery G2 must exclude `readReceiptById`, historical-receipt resolution, v4 migration, managed-event changes, receipt schema/runtime changes or duplication, provider-client code, and `.github/workflows/**`/fetch-depth changes.\n\nG2 must lock a closed, typed recovery decision/evidence boundary for this exact stale state rather than accepting a caller-authored complete `desired` state. The minimum semantic target remains: #359 CURRENT + blocking recovery hold + zero normal active lanes; #366 RETIRED/CLOSED_UNMERGED; #379 RETAINED/OPEN_DRAFT/INTERMEDIATE/completes_child=false with exact candidate binding; old E3-003 NON_CONVERGENT with 2/2 consumed and further repair forbidden; no G4 active; E3 unaccepted; E4/S3-S6 blocked; parked proof-boundary root not launched.\n\nG2 must also lock:\n- deterministic #240/#359 rendering and digests only;\n- complete typed Web/GitHub/native evidence and movement rejection;\n- exactly two eventual Programme Apply body operations: #359 first, #240 parent last;\n- CAS/prewrite rebinding, partial-write fail-closed recovery, full readback and immediate zero delta;\n- existing receipt subsystem unchanged for the new recovery operation only;\n- source commit S followed by bootstrap-only commit B if implementation is later authorised;\n- hosted bootstrap/contract proof from checked-in workspace bytes, never historical parent Git-object lookup or widened checkout history;\n- separate exact S:path/digest provenance proof through full GitHub/G4 evidence;\n- merge-commit preservation of S if Web later accepts G4 and merge. Repository settings currently permit merge commits.\n\nG2 is READ-ONLY. It may inspect #379 only as non-authoritative design evidence. It must return an exact file allowlist/forbidden list, necessity for each allowed path, schema shapes, version-bump decision with evidence, commit plan, tests, hosted checks, G4 scope, merge method, Apply/CAS/readback contract and retirement rule.\n\nOLD_ROOT=E3-CANONICAL-HISTORICAL-RECEIPT-RESOLUTION-003\nOLD_ROOT_DISPOSITION=TERMINAL_NON_CONVERGENT\nREPAIR_BUDGET=2/2_CONSUMED\nREPAIR3_AUTHORISED=NO\n\nPARKED_ROOT=E3-HISTORICAL-RECEIPT-CI-PROOF-BOUNDARY-SIMPLIFICATION-004\nPARKED_ROOT_STATUS=NOT_LAUNCHED\n\nG3_RECOVERY_IMPLEMENTATION_AUTHORISED=NO_PENDING_G2\nPARKED_ROOT_G2_AUTHORISED=NO\nPROGRAMME_APPLY_AUTHORISED=NO\nG4_AUTHORISED=NO\nREADY_AUTHORISED=NO\nMERGE_AUTHORISED=NO\nNORMAL_PROGRAMME_PROGRESS_AUTHORISED=NO\n\nNEXT_ACTION=Run fresh recovery-only G2 Design Lock and return to Web.\nSECRET_CLASSIFICATION=none\n\nRefs #240\nRefs #379","5580538176":"## WEB / PR #379 REMAINS FROZEN — RECOVERY G2 CURRENT\n\nRUN=2026-09-08-toolkit-s2-e3-v5-projection-bootstrap-g1-adjudication\nRECOVERY_ROOT=E3-V5-PROGRAMME-PROJECTION-BOOTSTRAP-RECOVERY-001\nG2_LOCK=DL-S2-E3-V5-PROJECTION-BOOTSTRAP-RECOVERY-001\nG2_CURRENT=YES_READ_ONLY\n\nEXACT_HEAD=adca2ffec8322eb57afcd9f9fdc67210503ebcf1\nEXACT_TREE=2c712aa9c7c6e66a89bdd9d033acece5415fd575\nMAIN=c72028c63cc09dd07d3e522692065448b6b7dbb6\nPR_DISPOSITION=RETAIN_OPEN_DRAFT_UNMERGED_FROZEN\n\nWeb accepted the recovery G1 architecture with a scope refinement: a fresh minimal v5 projection-bootstrap PR from canonical main is preferred, but the G1 worker's proposed 32-file implementation footprint is not accepted as the G3 allowlist.\n\nThis PR remains non-authoritative design evidence only. G2 may inspect its v5 parser/renderer/schema ideas, but must treat reused fragments as new source and must not copy the candidate v5 surface contract wholesale. In particular, this recovery excludes this PR's historical-receipt `readReceiptById` work, v4 migration work, receipt runtime/schema changes, managed-event changes, provider/client work, workflow/fetch-depth changes, and broad package/plugin/local-bridge/version churn unless independently proven necessary.\n\nThe old root remains terminal non-convergent at 2/2 repairs and no Repair 3. No mutation of this branch, PR body/state, checks, reviews, or commits is authorised by recovery G2.\n\nPARENT_RECONCILIATION_INCOMPLETE=YES_PROJECTION_STALE\nREPAIR_BUDGET=2/2_CONSUMED\nREPAIR3_AUTHORISED=NO\nPARKED_ROOT=E3-HISTORICAL-RECEIPT-CI-PROOF-BOUNDARY-SIMPLIFICATION-004\nPARKED_ROOT_STATUS=NOT_LAUNCHED\n\nG3_RECOVERY_IMPLEMENTATION_AUTHORISED=NO_PENDING_G2\nPARKED_ROOT_G2_AUTHORISED=NO\nPROGRAMME_APPLY_AUTHORISED=NO\nG4_AUTHORISED=NO\nREADY_AUTHORISED=NO\nMERGE_AUTHORISED=NO\n\nSECRET_CLASSIFICATION=none\n\nRefs #240\nRefs #359","5580978455":"## WEB / PR #379 STILL FROZEN — SEPARATE RECOVERY G3 AUTHORISED\n\nRUN=2026-09-08-toolkit-s2-e3-v5-projection-bootstrap-recovery-g2-adjudication\nRECOVERY_ROOT=E3-V5-PROGRAMME-PROJECTION-BOOTSTRAP-RECOVERY-001\nCONTROLLING_CHILD_AUTHORITY=#359/5580972753\n\nEXACT_HEAD=adca2ffec8322eb57afcd9f9fdc67210503ebcf1\nEXACT_TREE=2c712aa9c7c6e66a89bdd9d033acece5415fd575\nMAIN=c72028c63cc09dd07d3e522692065448b6b7dbb6\nPR_DISPOSITION=RETAIN_OPEN_DRAFT_UNMERGED_FROZEN\n\nRecovery G2 is accepted with a Web-only write-safety amendment. GitHub issue PATCH is not provider CAS; later Apply, if separately authorised, will use the explicitly bounded `WEB_EXCLUSIVE_SINGLE_WRITER_RECOVERY_WINDOW` with residual external race disclosed. No Apply is authorised now.\n\nA separate fresh recovery G3 is authorised from canonical main using exactly the accepted nine-path recovery lock, with no version bump and source S + bootstrap-only B commits. That G3 is NOT a mutation or Repair 3 of this PR.\n\nThis PR remains non-authoritative design evidence only. Do not mutate its branch, commits, body, state, checks or reviews. Do not import its historical-receipt `readReceiptById` or migration work into the recovery core.\n\nREPAIR_BUDGET=2/2_CONSUMED\nREPAIR3_AUTHORISED=NO\nPROGRAMME_APPLY_AUTHORISED=NO\nG4_AUTHORISED=NO\nREADY_AUTHORISED=NO\nMERGE_AUTHORISED=NO\nPARENT_RECONCILIATION_INCOMPLETE=YES_PROJECTION_STALE\n\nPARKED_ROOT=E3-HISTORICAL-RECEIPT-CI-PROOF-BOUNDARY-SIMPLIFICATION-004\nPARKED_ROOT_STATUS=NOT_LAUNCHED\n\nSECRET_CLASSIFICATION=none\n\nRefs #240\nRefs #359","5579264600":"## WEB REPAIR-1 BLOCKED ADJUDICATION / FINAL REPAIR-2 LINK\n\nAUTHORITY_RECORD=2026-09-08-web-e3-003-final-repair2\nROOT=E3-CANONICAL-HISTORICAL-RECEIPT-RESOLUTION-003\n\nControlling authority: [Child #359 comment 5579252134](https://github.com/weijunswj/ai-agent-toolkit/issues/359#issuecomment-5579252134).\nVerified parent mirror: [#240 comment 5579259452](https://github.com/weijunswj/ai-agent-toolkit/issues/240#issuecomment-5579259452).\n\nThis adjudication binds Repair-1 head fd8413b75d9977b6a9c3d9d68c92c48c834a7e81 / tree 6deec8ef47b34152ec18129a0885d4ef2dc1e91d against main c72028c63cc09dd07d3e522692065448b6b7dbb6.\n\nRepair 1 is not G3-complete. Its original two defects are closed, but both Validate checks remain failed. Web reproduced the recovery assertion locally and also found a bootstrap-resolution defect:\n- Programme recovery requires TERMINAL_UNCONSUMED, with replay_allowed=false and advances_state=false; TERMINAL is the lower receipt-store status.\n- The actual bootstrap contains raw hash d65cd2ad008998ed79921c21c2d55195eabbd63b70cc098336966120bb33266a, whereas the existing resolver requires canonical-JSON hash 50c1b3eb438ac22e3da52367ae08f76d5abc622e8c8da75312b4f36673f3c494. Exact pinned resolution fails until the bootstrap value is corrected. The PR description's earlier hash claim is not evidence of resolver acceptance.\n\nFinal Repair 2 may change only the programme-bootstrap-recovery test and then the bootstrap revision/digest, as fully specified in the child authority. Required append-only sequence: current head -> R2-SOURCE (test only) -> R2-BOOTSTRAP (bootstrap only). No runtime, schema, contract, policy, workflow, version or other file changes.\n\nBudget remains 1/2 consumed until the first Repair-2 source mutation, then 2/2. No Repair 3. Final repaired-head validation and fresh Web adjudication are required before any G4.\n\nPR remains OPEN/DRAFT/INTERMEDIATE; completes_child=false.\nG4_AUTHORISED=NO_PENDING_WEB_ADJUDICATION\nREADY_AUTHORISED=NO\nMERGE_AUTHORISED=NO\nPROGRAMME_APPLY_AUTHORISED=NO\nPARENT_RECONCILIATION_INCOMPLETE=YES_RECOVERY_IN_PROGRESS\nSECRET_CLASSIFICATION=none\n\nNo worker was launched and no candidate or managed programme state was changed by this publication.","5579508129":"## G3 FINAL REPAIR-2 EVIDENCE / PARENT MIRROR\n\nParent mirror: https://github.com/weijunswj/ai-agent-toolkit/issues/240#issuecomment-5579503003\n\nR2-BOOTSTRAP exact head: adca2ffec8322eb57afcd9f9fdc67210503ebcf1\nR2-SOURCE: 0a0990d7dd2e48c8522a6dfd20dc60a28b33f8ed\n\nHosted Validate and Validate toolkit both fail only at the new actual-bootstrap regression: the test asks a shallow checkout for the pinned R2-SOURCE Git object and receives status 128. The checked-in resolver, canonical digest proof, receipt lookup/tamper coverage, retained-v3 historical resolution, and all four analysis/security contexts otherwise pass. Repair budget is 2/2; no Repair 3 is authorised.\n\nRESULT=NON_CONVERGENCE_DECISION_REQUIRED\nG4_AUTHORISED=NO_PENDING_WEB_ADJUDICATION\nREADY_AUTHORISED=NO\nMERGE_AUTHORISED=NO\nPROGRAMME_APPLY_AUTHORISED=NO","5579738186":"## WEB / PR #379 NON-CONVERGENCE DISPOSITION\n\nRUN=2026-09-08-toolkit-s2-e3-non-convergence-adjudication\nOLD_ROOT=E3-CANONICAL-HISTORICAL-RECEIPT-RESOLUTION-003\nOLD_ROOT_DISPOSITION=TERMINAL_NON_CONVERGENT\nREPAIR_BUDGET=2/2_CONSUMED\nREPAIR3_AUTHORISED=NO\nEXACT_HEAD=adca2ffec8322eb57afcd9f9fdc67210503ebcf1\nMAIN=c72028c63cc09dd07d3e522692065448b6b7dbb6\n\nWEB_FINDING=The remaining hosted failure is confined to the Repair-2 actual-bootstrap regression invoking git cat-file/git show for a pinned parent revision unavailable in the hosted shallow checkout. Do not patch this as Repair 3 and do not change fetch depth merely to satisfy the regression.\n\nWEB_DECISION=Retain this PR OPEN/DRAFT/UNMERGED at the exact head. Preserve the 48-path candidate and its existing runtime/schema/receipt semantics.\n\nNEXT_ROOT_INTENT=E3-HISTORICAL-RECEIPT-CI-PROOF-BOUNDARY-SIMPLIFICATION-004\nNEXT_GATE_INTENT=G2_REENTRY\nG2_PURPOSE=Separate hosted workspace-byte resolver proof from full-history revision/object proof.\nG2_LAUNCH_AUTHORISED=NO_PENDING_PROGRAMME_RECONCILIATION\n\nPARENT_RECONCILIATION_INCOMPLETE=YES_PROJECTION_STALE\nREASON=#240 and #359 managed v5 bodies still project PR #366 / E3 G4 ACTIVE and must be reconciled against the current durable #379 chronology before a material gate transition.\n\nNo repository/code mutation, Repair 3, G2 implementation, G4, Ready, merge, finality or Programme Apply is authorised by this comment. Next action is a reconciliation-only control-plane pass and Web adjudication.\n\nSECRET_CLASSIFICATION=none\n\nRefs #240\nRefs #359","5579993168":"## WEB / PR #379 FROZEN DURING V5 PROJECTION BOOTSTRAP RECOVERY\n\nRUN=2026-09-08-toolkit-s2-e3-v5-projection-bootstrap-adjudication\nRECON_RESULT=ROUTE_UNAVAILABLE\n\nEXACT_HEAD=adca2ffec8322eb57afcd9f9fdc67210503ebcf1\nEXACT_TREE=2c712aa9c7c6e66a89bdd9d033acece5415fd575\nMAIN=c72028c63cc09dd07d3e522692065448b6b7dbb6\n\nWEB_CLASSIFICATION=The new blocker is a control-plane bootstrap gap outside this candidate's repair budget: current main lacks a trusted v5 live projection resolver/renderer and authoritative target-state mapping, while this candidate cannot certify or apply its own v5 projection authority.\n\nPR_DISPOSITION=RETAIN_OPEN_DRAFT_UNMERGED_FROZEN\nREPAIR_BUDGET=2/2_CONSUMED\nREPAIR3_AUTHORISED=NO\n\nPARKED_NEXT_ROOT=E3-HISTORICAL-RECEIPT-CI-PROOF-BOUNDARY-SIMPLIFICATION-004\nPARKED_NEXT_GATE=G2_REENTRY\n\nRECOVERY_ROOT=E3-V5-PROGRAMME-PROJECTION-BOOTSTRAP-RECOVERY-001\nRECOVERY_GATE=G1_READ_ONLY_ARCHITECTURE\nRECOVERY_G1_AUTHORISED=YES\n\nThe recovery review may inspect this PR's v5 implementation only as non-authoritative design evidence. It may not mutate this branch, rerun the exhausted same-root repair cycle, use this candidate to self-certify a managed projection, or perform Programme Apply.\n\nNo code mutation, Repair 3, G2 implementation, G4, Ready, merge, finality, or managed-body mutation is authorised here.\n\nSECRET_CLASSIFICATION=none\n\nRefs #240\nRefs #359"});

function digestText(value) { return crypto.createHash('sha256').update(value, 'utf8').digest('hex'); }
function clone(value) { return JSON.parse(JSON.stringify(value)); }
function withEvidenceDigest(value) {
  const next = clone(value);
  delete next.evidence_digest;
  return { ...value, evidence_digest: programme.digestValue(next) };
}
function parsedSources() {
  assert.equal(typeof PARENT_BODY, 'string');
  assert.equal(typeof CHILD_BODY, 'string');
  const parent = programme.parseParentV5Body(PARENT_BODY, { repository, parent_issue: 240 });
  const child = programme.parseChildV5Body(CHILD_BODY, { repository, parent_issue: 240 });
  assert.equal(parent.ok, true, parent.code);
  assert.equal(child.ok, true, child.code);
  return { parent, child };
}
function pagination(evidence) {
  return Object.fromEntries(programme.PAGINATION_KEYS.map((key) => [
    key,
    programme.buildPaginationEvidence(key, evidence),
  ]));
}
function webAuthority() {
  const records = [...decision.web_authority.controlling, ...decision.web_authority.predecessor];
  return records.map((entry) => ({
    issue: entry.issue,
    comment_id: entry.comment_id,
    body: entry.issue === 379
      ? PR379_COMMENT_BODIES[String(entry.comment_id)]
      : entry.comment_id === 5580972753 || entry.comment_id === 5580530088
        ? PR379_COMMENT_BODIES['issue-359-' + String(entry.comment_id)]
        : PR379_COMMENT_BODIES['issue-240-' + String(entry.comment_id)],
    body_digest: entry.body_digest,
  }));
}
function pr379Facts() {
  return {
    repository,
    pr: 379,
    state: 'OPEN',
    draft: true,
    merged: false,
    merged_at: null,
    head: programme.FROZEN_HEAD,
    tree: programme.FROZEN_TREE,
    branch: programme.FROZEN_BRANCH,
    base_ref: 'main',
    base_sha: programme.MAIN_SHA,
    changed_files: 48,
    candidate: clone(decision.pr_379.candidate),
    reviews: [{
      ...clone(programme.PR379_REVIEW_FACTS[0]),
      body: PR379_REVIEW_BODY,
    }],
    threads: [],
    comments: programme.PR379_COMMENT_FACTS.map((entry) => ({
      ...clone(entry),
      body: PR379_COMMENT_BODIES[String(entry.id)],
    })),
    checks: clone(programme.PR379_CHECK_FACTS),
    facts_digest: decision.pr_379.facts_digest,
    complete: true,
  };
}
function pr366Facts() {
  return {
    pr: 366,
    status: 'RETIRED',
    github_state: 'CLOSED',
    draft: true,
    merged: false,
    merged_at: null,
    merge_commit: null,
    role: 'INTERMEDIATE',
    completes_child: false,
    candidate: null,
    head: programme.PR366_HEAD,
    tree: programme.PR366_TREE,
    base_ref: 'main',
    base_sha: programme.PR366_BASE_SHA,
    complete: true,
  };
}
function snapshotState(state) {
  const child = state.children.find((item) => item.issue === 359);
  const lane = state.active_lanes.find((item) => item.child_issue === 359);
  return {
    lifecycle: child.lifecycle,
    finality: child.finality.state,
    gate_state: state.recovery ? 'HELD' : lane ? lane.gate_state : 'NONE',
    normal_active_lanes: state.active_lanes.length,
    active_blocking_recovery_hold: Boolean(state.recovery),
  };
}
function makeEvidence(snapshot = 'BEFORE_CHILD', continuation = null) {
  const source = parsedSources();
  const targetState = programme.buildRecoveryTargetState(source.parent.state);
  assert.ok(targetState);
  const targetRendered = programme.renderProgrammeV5(targetState);
  assert.equal(targetRendered.ok, true, targetRendered.code);
  const targetParent = programme.parseParentV5Body(targetRendered.parent, { repository, parent_issue: 240 });
  const targetChild = programme.parseChildV5Body(targetRendered.child, { repository, parent_issue: 240 });
  assert.equal(targetParent.ok, true, targetParent.code);
  assert.equal(targetChild.ok, true, targetChild.code);
  const useTargetParent = snapshot === 'PARENT_WRITTEN_ACK_LOST';
  const useTargetChild = snapshot !== 'BEFORE_CHILD';
  const parent = useTargetParent ? targetParent : source.parent;
  const child = useTargetChild ? targetChild : source.child;
  const parentState = useTargetParent ? targetState : source.parent.state;
  const childState = useTargetParent || useTargetChild ? snapshotState(targetState) : snapshotState(source.parent.state);
  const evidence = {
    schema: programme.EVIDENCE_SCHEMA,
    recovery_root: programme.RECOVERY_ROOT,
    lock: programme.LOCK,
    decision_digest: programme.digestValue(decision),
    snapshot,
    repository,
    parent_issue: 240,
    child_issue: 359,
    parent: {
      issue: 240,
      raw_body: useTargetParent ? targetRendered.parent : PARENT_BODY,
      body_digest: parent.body_digest,
      canonical_digest: parent.envelope.canonical_digest,
      revision: programme.SOURCE_PARENT_REVISION,
      state: clone(parentState),
      native_children: [358, 359, 360, 361, 362, 363],
      relationships: { child_issue: 359, child_is_native_sub_issue: true, parent_issue: 240, sole_current: true },
      prefix_digest: parent.prefix_digest,
      suffix_digest: parent.suffix_digest,
      complete: true,
    },
    child: {
      issue: 359,
      raw_body: useTargetChild ? targetRendered.child : CHILD_BODY,
      body_digest: child.body_digest,
      canonical_digest: child.envelope.canonical_digest,
      revision: programme.SOURCE_CHILD_REVISION,
      labels: ['current'],
      native_parent: 240,
      relationships: { child_issue: 359, child_is_native_sub_issue: true, parent_issue: 240, sole_current: true },
      sole_current: true,
      dependencies: [],
      state: childState,
      projection: clone(child.envelope),
      prefix_digest: child.prefix_digest,
      suffix_digest: child.suffix_digest,
      complete: true,
    },
    pr_366: pr366Facts(),
    pr_379: pr379Facts(),
    web_authority: webAuthority(),
    pagination: null,
    provider_evidence: {
      check_runs: {
        endpoint_or_query_identity: programme.PAGINATION_COLLECTIONS.checks.endpoint,
        field: programme.CHECK_RUNS_TOTAL_FIELD,
        value: 6,
      },
    },
    collector: {
      kind: 'WEB_AUTHENTICATED_GITHUB_COLLECTION',
      identity: 'github-web-readonly-adapter',
      version: 'v1',
      authenticated: true,
      provider_client_used: false,
    },
    authority_digest: decision.web_authority.digest,
    continuation,
    evidence_digest: null,
  };
  evidence.pagination = pagination(evidence);
  return withEvidenceDigest(evidence);
}
function continuationFromPreview(preview) {
  const operation = preview.operations[0];
  return {
    authority_digest: preview.authority_digest,
    child_operation_digest: operation.receipt_logical_operation_digest,
    child_operation_id: operation.operation_id,
    decision_digest: preview.decision_digest,
    preview_id: preview.preview_id,
    receipt_operation_digest: operation.receipt_logical_operation_digest,
    receipt_operation_id: 'operation-recovery-test',
    safety_mode: programme.WRITE_SAFETY_MODE,
  };
}
function replaceEvidence(value, pathParts, replacement) {
  const next = clone(value);
  let cursor = next;
  for (let index = 0; index < pathParts.length - 1; index += 1) cursor = cursor[pathParts[index]];
  cursor[pathParts[pathParts.length - 1]] = replacement;
  return withEvidenceDigest(next);
}

test('locked source identity, exact stale digests, and parser coverage', () => {
  const source = parsedSources();
  assert.equal(source.parent.body_digest, programme.SOURCE_PARENT_BODY_DIGEST);
  assert.equal(source.child.body_digest, programme.SOURCE_CHILD_BODY_DIGEST);
  assert.equal(source.parent.envelope.canonical_digest, programme.SOURCE_CANONICAL_DIGEST);
  assert.equal(source.parent.envelope.canonical_digest, source.child.envelope.canonical_digest);
  assert.equal(source.parent.state.design_lock, 'DL-S2-GITHUB-PROGRAM-SURFACE-RECOVERY-003');
});

test('held CURRENT with zero normal lanes requires the eligible blocking hold', () => {
  const source = parsedSources();
  const target = programme.buildRecoveryTargetState(source.parent.state);
  assert.equal(programme.validateCanonicalStateV5(target).ok, true);
  const withoutHold = clone(target);
  withoutHold.children.find((item) => item.issue === 359).holds = [];
  assert.equal(programme.validateCanonicalStateV5(withoutHold).code, 'V5_CURRENT_ZERO_LANE_HOLD_REQUIRED');
  const withoutRecovery = clone(target);
  delete withoutRecovery.recovery;
  assert.equal(programme.validateCanonicalStateV5(withoutRecovery).code, 'V5_CURRENT_ZERO_LANE_HOLD_REQUIRED');
  const hold = target.children.find((item) => item.issue === 359).holds[0];
  assert.deepEqual(hold, {
    id: programme.RECOVERY_ROOT,
    root: programme.RECOVERY_ROOT,
    lock: programme.LOCK,
    kind: 'BLOCKING',
    scope: 'PROGRAMME_PROJECTION_RECOVERY',
    active: true,
    blocks_normal_lanes: true,
    evidence_ref: programme.HOLD_EVIDENCE_REF,
    summary: 'Managed v5 parent and child projections are stale and remain held pending separately authorised recovery.',
  });
  assert.equal(target.evidence_refs.some((item) => item.id === programme.HOLD_EVIDENCE_REF
    && item.kind === 'WEB' && item.reference === 'github:issue-comment:359:5580530088'), true);
  for (const field of ['root', 'lock', 'kind', 'scope', 'evidence_ref']) {
    const malformed = clone(target);
    delete malformed.children.find((item) => item.issue === 359).holds[0][field];
    assert.equal(programme.validateCanonicalStateV5(malformed).ok, false, field);
  }
  for (const [field, value] of [
    ['root', 'wrong-root'],
    ['lock', 'wrong-lock'],
    ['kind', 'ADVISORY'],
    ['scope', 'OTHER_SCOPE'],
    ['active', false],
    ['blocks_normal_lanes', false],
    ['evidence_ref', 'dangling-evidence'],
  ]) {
    const malformed = clone(target);
    malformed.children.find((item) => item.issue === 359).holds[0][field] = value;
    assert.equal(programme.validateCanonicalStateV5(malformed).ok, false, field);
  }
  const nonWebEvidence = clone(target);
  nonWebEvidence.evidence_refs.find((item) => item.id === programme.HOLD_EVIDENCE_REF).kind = 'COMMIT';
  assert.equal(programme.validateCanonicalStateV5(nonWebEvidence).ok, false);
  const conflictingHolds = clone(target);
  conflictingHolds.children.find((item) => item.issue === 359).holds.push(clone(hold));
  assert.equal(programme.validateCanonicalStateV5(conflictingHolds).ok, false);
});

test('fixed retained and historical PR semantics are exact', () => {
  const source = parsedSources();
  const target = programme.buildRecoveryTargetState(source.parent.state);
  const child = target.children.find((item) => item.issue === 359);
  assert.deepEqual(child.pr_registry[0], {
    accepted_evidence_ref: null,
    candidate: null,
    completes_child: false,
    draft: true,
    epoch_id: 'E3',
    github_state: 'CLOSED',
    merged: false,
    pr: 366,
    retention_evidence_ref: null,
    retirement_evidence_ref: programme.RECOVERY_EVIDENCE_REF,
    role: 'INTERMEDIATE',
    status: 'RETIRED',
  });
  assert.deepEqual(child.pr_registry[1], {
    accepted_evidence_ref: null,
    candidate: decision.pr_379.candidate,
    completes_child: false,
    draft: true,
    epoch_id: 'E3',
    github_state: 'OPEN',
    merged: false,
    pr: 379,
    retention_evidence_ref: programme.RETENTION_EVIDENCE_REF,
    retirement_evidence_ref: null,
    role: 'INTERMEDIATE',
    status: 'RETAINED',
  });
  const malformed = clone(target);
  malformed.children.find((item) => item.issue === 359).pr_registry[1].status = 'ACTIVE';
  assert.equal(programme.validateCanonicalStateV5(malformed).ok, false);
  const malformedCandidate = clone(target);
  delete malformedCandidate.children.find((item) => item.issue === 359).pr_registry[1].candidate.tree;
  assert.equal(programme.validateCanonicalStateV5(malformedCandidate).ok, false);
  for (const replacement of [null, 'dangling-retention-evidence', 'non-web-retention']) {
    const malformedRetention = clone(target);
    malformedRetention.children.find((item) => item.issue === 359).pr_registry[1].retention_evidence_ref = replacement;
    if (replacement === 'non-web-retention') {
      malformedRetention.evidence_refs.find((item) => item.id === programme.RETENTION_EVIDENCE_REF).kind = 'COMMIT';
    }
    assert.equal(programme.validateCanonicalStateV5(malformedRetention).ok, false, replacement);
  }
  const malformed366 = clone(target);
  malformed366.children.find((item) => item.issue === 359).pr_registry[0].retention_evidence_ref = programme.RETENTION_EVIDENCE_REF;
  assert.equal(programme.validateCanonicalStateV5(malformed366).ok, false);
  assert.equal(target.evidence_refs.some((item) => item.id === programme.RETENTION_EVIDENCE_REF
    && item.kind === 'WEB' && item.reference === 'github:issue-comment:379:5580538176'), true);
});

test('old root is typed terminal non-convergence and parked root is not launched', () => {
  const source = parsedSources();
  const target = programme.buildRecoveryTargetState(source.parent.state);
  assert.deepEqual(target.recovery.old_root, {
    root: programme.OLD_ROOT,
    disposition: 'NON_CONVERGENT',
    terminal: true,
    repair_budget: { used: 2, limit: 2, further_repair_authorised: false },
  });
  assert.deepEqual(target.recovery.parked_root, {
    root: programme.PARKED_ROOT,
    status: 'NOT_LAUNCHED',
  });
});

test('fixed semantic delta removes the normal lane and keeps unrelated queued children', () => {
  const source = parsedSources();
  const target = programme.buildRecoveryTargetState(source.parent.state);
  assert.deepEqual(target.active_lanes, []);
  assert.equal(target.children.find((item) => item.issue === 359).lifecycle, 'CURRENT');
  assert.deepEqual(target.children.filter((item) => item.issue >= 360).map((item) => item.lifecycle), ['QUEUED', 'QUEUED', 'QUEUED', 'QUEUED']);
  assert.deepEqual(target.children.find((item) => item.issue === 360).dependencies, source.parent.state.children.find((item) => item.issue === 360).dependencies);
  assert.equal(target.children.find((item) => item.issue === 359).finality.state, 'HELD');
});

test('decision is closed and rejects caller-controlled state shapes', () => {
  assert.equal(programme.validateDecision(decision).ok, true);
  const extra = { ...clone(decision), desired: {} };
  assert.equal(programme.validateDecision(extra).ok, false);
  const changed = clone(decision);
  changed.write_safety.provider_cas_claim = true;
  assert.equal(programme.validateDecision(changed).ok, false);
  assert.equal(Object.prototype.hasOwnProperty.call(decision, 'desired'), false);
});

test('successful stale preview has exactly two ordered body operations', () => {
  const evidence = makeEvidence();
  const preview = programme.projectionBootstrapRecovery.preview({ decision, evidence });
  assert.equal(preview.ok, true, preview.code);
  assert.equal(preview.operation_count, 2);
  assert.deepEqual(preview.operation_order, [359, 240]);
  assert.deepEqual(preview.operations.map((operation) => operation.issue), [359, 240]);
  assert.equal(preview.operations[0].order, 1);
  assert.equal(preview.operations[1].order, 2);
  assert.equal(preview.write_safety.mode, programme.WRITE_SAFETY_MODE);
  assert.equal(preview.write_safety.provider_cas_claim, false);
  assert.equal(preview.receipt.operation_kind, 'IDEMPOTENT_SET');
  assert.equal(preview.receipt.safety_class, 'IDEMPOTENT');
  assert.equal(preview.receipt.provider_cas_claim, false);
  assert.equal(preview.receipt.source_changed, false);
  assert.equal(preview.self_retirement_fence.exact_target_only, true);
});

test('identical inputs render and preview deterministically', () => {
  const source = parsedSources();
  const target = programme.buildRecoveryTargetState(source.parent.state);
  assert.deepEqual(programme.renderProgrammeV5(target), programme.renderProgrammeV5(target));
  const evidence = makeEvidence();
  assert.deepEqual(
    programme.projectionBootstrapRecovery.preview({ decision, evidence }),
    programme.projectionBootstrapRecovery.preview({ decision: clone(decision), evidence: clone(evidence) }),
  );
});

test('unrelated bytes outside managed blocks are preserved', () => {
  const source = parsedSources();
  const target = programme.buildRecoveryTargetState(source.parent.state);
  const rendered = programme.renderProgrammeV5(target);
  const parentWithOutside = 'owner-prefix\n' + rendered.parent + '\nowner-suffix';
  const childWithOutside = 'owner-prefix\n' + rendered.child + '\nowner-suffix';
  const parentParsed = programme.parseParentV5Body(parentWithOutside, { repository, parent_issue: 240 });
  const childParsed = programme.parseChildV5Body(childWithOutside, { repository, parent_issue: 240 });
  assert.equal(parentParsed.prefix, 'owner-prefix\n');
  assert.equal(parentParsed.suffix, '\nowner-suffix');
  assert.equal(childParsed.prefix, 'owner-prefix\n');
  assert.equal(childParsed.suffix, '\nowner-suffix');
  assert.equal(parentParsed.managed, rendered.parent);
  assert.equal(childParsed.managed, rendered.child);
});

test('incomplete, stale, contradictory, and unpaginated evidence fail closed', () => {
  const evidence = makeEvidence();
  assert.equal(programme.validateEvidence(evidence, decision).ok, true);
  assert.equal(programme.validateEvidence(replaceEvidence(evidence, ['pagination', 'comments', 'complete'], false), decision).ok, false);
  assert.equal(programme.validateEvidence(replaceEvidence(evidence, ['parent', 'complete'], false), decision).ok, false);
  assert.equal(programme.validateEvidence(replaceEvidence(evidence, ['parent', 'canonical_digest'], 'f'.repeat(64)), decision).ok, false);
  assert.equal(programme.validateEvidence(replaceEvidence(evidence, ['authority_digest'], 'f'.repeat(64)), decision).ok, false);
  assert.equal(programme.validateEvidence(replaceEvidence(evidence, ['collector', 'authenticated'], false), decision).ok, false);
});

test('pagination evidence proves identity, counts, ordered pages, progression, totals, and inventory', () => {
  const evidence = makeEvidence();
  const mutate = (pathParts, replacement) => programme.validateEvidence(replaceEvidence(evidence, pathParts, replacement), decision).ok;
  assert.equal(mutate(['pagination', 'parent', 'endpoint_or_query_identity'], 'github:issues/other'), false);
  assert.equal(mutate(['pagination', 'parent', 'page_size'], 50), false);
  assert.equal(mutate(['pagination', 'parent', 'page_count'], 2), false);
  assert.equal(mutate(['pagination', 'parent', 'retrieved_count'], 0), false);
  assert.equal(mutate(['pagination', 'parent', 'ordered_page_digests', 0, 'digest'], 'f'.repeat(64)), false);
  assert.equal(mutate(['pagination', 'parent', 'inventory_digest'], 'f'.repeat(64)), false);
  assert.equal(mutate(['pagination', 'native_children', 'progression', 'pages', 0, 'page'], 2), false);
  assert.equal(mutate(['pagination', 'parent', 'transport_mode'], 'LINK'), false);
  assert.equal(mutate(['pagination', 'parent', 'progression'], { style: 'LINK', pages: [{ page: 1, next_url: null }] }), false);
  assert.equal(mutate(['pagination', 'comments', 'terminal_state', 'has_next_page'], true), false);
  assert.equal(mutate(['pagination', 'comments', 'terminal_state', 'next_url'], 'https://api.github.com/issues?page=2'), false);
  assert.equal(mutate(['pagination', 'parent', 'server_total', 'value'], 999), false);
  assert.equal(mutate(['pagination', 'threads', 'server_total'], { status: 'AVAILABLE', value: 0 }), false);
  assert.equal(mutate(['pagination', 'threads', 'server_total'], { status: 'UNAVAILABLE' }), false);
  assert.equal(mutate(['pagination', 'review_thread_comments', 'complete'], false), false);
  const reordered = clone(evidence);
  reordered.pagination.parent.page_count = 2;
  reordered.pagination.parent.ordered_page_digests.push({ page: 2, digest: 'f'.repeat(64) });
  reordered.pagination.parent.progression = {
    style: 'LINK',
    pages: [
      { page: 1, next_url: 'https://api.github.com/issues?page=2' },
      { page: 2, next_url: null },
    ],
  };
  assert.equal(programme.validateEvidence(withEvidenceDigest(reordered), decision).ok, false);
  const completeOnly = clone(evidence);
  completeOnly.pagination.parent = { complete: true };
  assert.equal(programme.validateEvidence(withEvidenceDigest(completeOnly), decision).ok, false);
});

test('pagination transport and provider totals remain truthful', () => {
  const evidence = makeEvidence();
  const mutate = (pathParts, replacement) => programme.validateEvidence(replaceEvidence(evidence, pathParts, replacement), decision).ok;
  for (const key of ['parent', 'child', 'pr366', 'pr379', 'web_authority']) {
    assert.equal(evidence.pagination[key].transport_mode, 'DIRECT', key);
    assert.equal(evidence.pagination[key].page_size, null, key);
    assert.equal(evidence.pagination[key].progression, null, key);
    assert.equal(evidence.pagination[key].terminal_state, null, key);
    assert.equal(evidence.pagination[key].provider_total_count, null, key);
    assert.deepEqual(evidence.pagination[key].server_total, { status: 'UNAVAILABLE', value: null }, key);
    assert.equal(mutate(['pagination', key, 'server_total'], { status: 'AVAILABLE', value: evidence.pagination[key].retrieved_count }), false, key);
    assert.equal(mutate(['pagination', key, 'provider_total_count'], evidence.pagination[key].retrieved_count), false, key);
  }
  for (const key of ['native_children', 'current_label', 'reviews', 'threads', 'review_thread_comments', 'comments', 'checks']) {
    assert.equal(evidence.pagination[key].transport_mode, 'LINK', key);
    assert.equal(evidence.pagination[key].page_size, 100, key);
    assert.equal(evidence.pagination[key].progression.style, 'LINK', key);
    assert.equal(evidence.pagination[key].terminal_state.has_next_page, false, key);
  }
  assert.deepEqual(evidence.pagination.checks.server_total, { status: 'AVAILABLE', value: 6 });
  assert.equal(evidence.pagination.checks.provider_total_count, 6);
  assert.equal(evidence.provider_evidence.check_runs.value, 6);
  assert.equal(mutate(['pagination', 'checks', 'server_total'], { status: 'UNAVAILABLE', value: null }), false);
  assert.equal(mutate(['provider_evidence', 'check_runs', 'value'], 7), false);
  assert.equal(mutate(['pagination', 'checks', 'provider_total_count'], 7), false);
  assert.equal(mutate(['pagination', 'comments', 'server_total'], { status: 'AVAILABLE', value: 6 }), false);
  assert.equal(mutate(['pagination', 'comments', 'provider_total_count'], 6), false);
  assert.equal(mutate(['pagination', 'parent', 'page_size'], 100), false);
  assert.equal(mutate(['pagination', 'parent', 'progression'], { style: 'LINK', pages: [{ page: 1, next_url: null }] }), false);
  assert.equal(mutate(['pagination', 'comments', 'page_size'], null), false);
  assert.equal(mutate(['pagination', 'comments', 'progression'], null), false);
  assert.equal(mutate(['pagination', 'comments', 'terminal_state'], null), false);
  const missingProviderTotal = clone(evidence);
  delete missingProviderTotal.provider_evidence.check_runs.value;
  assert.equal(programme.validateEvidence(withEvidenceDigest(missingProviderTotal), decision).ok, false);
});

test('PR movement, check/review/thread/comment movement, labels, and native relationship movement fail closed', () => {
  const evidence = makeEvidence();
  assert.equal(programme.validateEvidence(replaceEvidence(evidence, ['pr_379', 'head'], 'f'.repeat(40)), decision).code, 'RECOVERY_PR379_INVALID');
  const reviewMoved = clone(evidence);
  reviewMoved.pr_379.reviews[0].state = 'APPROVED';
  assert.equal(programme.validateEvidence(withEvidenceDigest(reviewMoved), decision).code, 'RECOVERY_PR379_REVIEW_MOVED');
  const commentMoved = clone(evidence);
  commentMoved.pr_379.comments[0].body = 'moved';
  assert.equal(programme.validateEvidence(withEvidenceDigest(commentMoved), decision).code, 'RECOVERY_PR379_COMMENT_MOVED');
  const checksMoved = clone(evidence);
  checksMoved.pr_379.checks[0].conclusion = 'failure';
  assert.equal(programme.validateEvidence(withEvidenceDigest(checksMoved), decision).code, 'RECOVERY_PR379_CHECK_MOVED');
  assert.equal(programme.validateEvidence(replaceEvidence(evidence, ['pr_379', 'threads'], [{ id: 'thread-1' }]), decision).code, 'RECOVERY_PR379_THREAD_MOVED');
  assert.equal(programme.validateEvidence(replaceEvidence(evidence, ['child', 'labels'], ['current', 'other']), decision).code, 'RECOVERY_CHILD_EVIDENCE_INVALID');
  assert.equal(programme.validateEvidence(replaceEvidence(evidence, ['child', 'native_parent'], 1), decision).code, 'RECOVERY_CHILD_EVIDENCE_INVALID');
  assert.equal(programme.validateEvidence(replaceEvidence(evidence, ['parent', 'native_children'], [358, 359]), decision).code, 'RECOVERY_PARENT_EVIDENCE_INVALID');
});

test('partial write classifications require the same preview, authority, operation, and receipt binding', () => {
  const before = makeEvidence();
  const first = programme.projectionBootstrapRecovery.preview({ decision, evidence: before });
  assert.equal(first.ok, true, first.code);
  const continuation = continuationFromPreview(first);
  const childWritten = makeEvidence('CHILD_WRITTEN_PARENT_STALE', continuation);
  const continuationPreview = programme.projectionBootstrapRecovery.preview({ decision, evidence: childWritten });
  assert.equal(continuationPreview.ok, true, continuationPreview.code);
  assert.equal(continuationPreview.operation_count, 1);
  assert.deepEqual(continuationPreview.operation_order, [240]);
  const badContinuation = clone(childWritten);
  badContinuation.continuation.preview_id = 'f'.repeat(64);
  assert.equal(programme.projectionBootstrapRecovery.preview({ decision, evidence: withEvidenceDigest(badContinuation) }).ok, false);
  const badChildOperationDigest = clone(childWritten);
  badChildOperationDigest.continuation.child_operation_digest = 'f'.repeat(64);
  assert.equal(programme.projectionBootstrapRecovery.preview({ decision, evidence: withEvidenceDigest(badChildOperationDigest) }).ok, false);
  const wrongCombo = clone(before);
  wrongCombo.child.raw_body = continuationPreview.target.bodies.child;
  wrongCombo.child.body_digest = digestText(wrongCombo.child.raw_body);
  wrongCombo.child.canonical_digest = continuationPreview.target.canonical_digest;
  const wrongParsed = programme.parseChildV5Body(wrongCombo.child.raw_body, { repository, parent_issue: 240 });
  wrongCombo.child.projection = wrongParsed.envelope;
  wrongCombo.child.prefix_digest = wrongParsed.prefix_digest;
  wrongCombo.child.suffix_digest = wrongParsed.suffix_digest;
  wrongCombo.snapshot = 'BEFORE_CHILD';
  assert.equal(programme.projectionBootstrapRecovery.preview({ decision, evidence: withEvidenceDigest(wrongCombo) }).ok, false);
});

test('lost acknowledgement reads the exact target and returns zero operations', () => {
  const before = makeEvidence();
  const first = programme.projectionBootstrapRecovery.preview({ decision, evidence: before });
  const lostAck = makeEvidence('PARENT_WRITTEN_ACK_LOST', continuationFromPreview(first));
  const reconciled = programme.projectionBootstrapRecovery.preview({ decision, evidence: lostAck });
  assert.equal(reconciled.ok, true, reconciled.code);
  assert.equal(reconciled.code, 'PROGRAMME_ZERO_DELTA');
  assert.equal(reconciled.operation_count, 0);
  assert.deepEqual(reconciled.operations, []);
  assert.equal(reconciled.recovery_retired, true);
  assert.equal(reconciled.duplicate_write, false);
  assert.equal(reconciled.readback_required, true);
});

test('self-retirement rejects a target with an unrelated canonical change', () => {
  const before = makeEvidence();
  const first = programme.projectionBootstrapRecovery.preview({ decision, evidence: before });
  const target = makeEvidence('PARENT_WRITTEN_ACK_LOST', continuationFromPreview(first));
  const changed = clone(target);
  changed.parent.state.children.find((item) => item.issue === 360).summary = 'unrelated movement';
  assert.equal(programme.validateEvidence(withEvidenceDigest(changed), decision).ok, false);
});

test('receipt subsystem remains unchanged and the binding is truthful idempotent semantics', () => {
  const receiptPath = path.join(__dirname, '..', 'scripts', 'toolkit-github-program-receipt.cjs');
  const before = digestText(fs.readFileSync(receiptPath, 'utf8'));
  const descriptor = programme.buildReceiptOperationDescriptor({
    issue: 359,
    authority_digest: decision.web_authority.digest,
    source_body_digest: programme.SOURCE_CHILD_BODY_DIGEST,
    source_revision: programme.SOURCE_CHILD_REVISION,
    target_body_digest: 'f'.repeat(64),
  });
  assert.doesNotThrow(() => receipt.validateOperationDescriptor(descriptor));
  assert.equal(descriptor.operation_kind, 'IDEMPOTENT_SET');
  assert.equal(descriptor.safety_class, 'IDEMPOTENT');
  assert.equal(descriptor.cas_digest, programme.digestValue({
    mode: programme.WRITE_SAFETY_MODE,
    authority_digest: decision.web_authority.digest,
    source_body_digest: programme.SOURCE_CHILD_BODY_DIGEST,
    source_revision: programme.SOURCE_CHILD_REVISION,
  }));
  assert.equal(descriptor.adapter_identity_digest, programme.digestValue({
    adapter: 'github-web-readonly-adapter',
    mode: programme.WRITE_SAFETY_MODE,
    provider_cas_claim: false,
  }));
  assert.equal(receipt.OPERATION_KINDS.includes('CONDITIONAL_PROVIDER_UPDATE'), true);
  assert.equal(receipt.SAFETY_CLASSES.includes('CAS'), true);
  assert.equal(programme.WRITE_SAFETY_MODE, 'WEB_EXCLUSIVE_SINGLE_WRITER_RECOVERY_WINDOW');
  assert.equal(digestText(fs.readFileSync(receiptPath, 'utf8')), before);
});

test('bootstrap proof uses workspace bytes and never requires a historical Git object', (t) => {
  const bootstrapPath = path.join(__dirname, '..', '..', '.github', 'ai-agent-toolkit-programme.json');
  if (!fs.existsSync(bootstrapPath)) {
    t.skip('bootstrap commit B is intentionally absent during source commit validation');
    return;
  }
  const bootstrap = JSON.parse(fs.readFileSync(bootstrapPath, 'utf8'));
  const contractPath = path.join(__dirname, '..', 'contracts', 'github-program-reconciler', 'programme-surface-contract-v5.json');
  const proof = programme.verifyBootstrapWorkspaceProof({
    bootstrap,
    contract_bytes: fs.readFileSync(contractPath, 'utf8'),
    workspace_revision: bootstrap.toolkit_contract.revision,
  });
  assert.equal(proof.ok, true, proof.code);
  assert.equal(proof.historical_git_object_required, false);
  assert.equal(proof.actual_workspace_bytes, true);
  const source = fs.readFileSync(path.join(__dirname, '..', 'scripts', 'toolkit-github-program-state-v5.cjs'), 'utf8');
  assert.doesNotMatch(source, /git show|git cat-file|fetch-depth|unshallow/);
});

test('accepted shared facade exposes v5 recovery without a second reconciler', () => {
  assert.equal(governance.programmeV5.projectionBootstrapRecovery, programme.projectionBootstrapRecovery);
  const runtime = governance.createRuntime({ repository });
  assert.equal(runtime.programmeV5.projectionBootstrapRecovery, programme.projectionBootstrapRecovery);
  assert.equal(programme.programmeV5.projectionBootstrapRecovery, programme.projectionBootstrapRecovery);
});
